<?php
if(!defined('LOYF_RUNTIME_DISPOSABLE')){define('LOYF_RUNTIME_DISPOSABLE',true);}require __DIR__.'/assertions.php';
global $wpdb;
loyf_assert(class_exists('YOSWC_Loyalty',false)&&!class_exists('YOWCL_Loyalty',false),'One actual installed Free owner');
$before=json_decode(file_get_contents(getenv('LOYF13_SNAPSHOT')),true);
$persistence=unserialize(file_get_contents(getenv('LOYF13_SNAPSHOT').'.persistence'));loyf_equal($persistence['meta'],$wpdb->get_results("SELECT * FROM {$wpdb->usermeta} ORDER BY umeta_id",ARRAY_A),'Premium fractional/dormant/ownership raw metadata survives Free activation');loyf_equal($persistence['rows'],$wpdb->get_results("SELECT * FROM {$wpdb->prefix}yo_loyalty_points_log ORDER BY id",ARRAY_A),'Premium nullable history retains exact rows/IDs');loyf_equal($persistence['roles'],$wpdb->get_row($wpdb->prepare("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",$wpdb->prefix.'user_roles'),ARRAY_A),'Premium raw role definitions survive Free');
foreach($before as $row){loyf_equal($row,$wpdb->get_row($wpdb->prepare("SELECT option_name,option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",$row['option_name']),ARRAY_A),'Premium origin raw option intact');}
foreach(YOWCL_Free_Migrations::features() as $f){loyf_assert(!YOWCL_Free_Migrations::ready($f),'Held '.$f);foreach(array('','_before','_resolution') as $suffix){loyf_equal(null,YOWCL_Free_Migrations::read(YOWCL_Free_Migrations::witness($f).$suffix),'No invented migration evidence');}}
$rows=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}yo_loyalty_points_log ORDER BY id",ARRAY_A);$sent=0;add_filter('pre_wp_mail',static function($v)use(&$sent){$sent++;return true;},PHP_INT_MAX);
$run=substr(wp_generate_uuid4(),0,8);$u=wp_insert_user(array('user_login'=>'held_'.$run,'user_email'=>'held-'.$run.'@example.invalid','user_pass'=>'disposable-only','role'=>'subscriber'));loyf_assert(!is_wp_error($u),'Held test customer');do_action('wp_login','held_'.$run,get_userdata($u));
$p=new WC_Product_Simple();$p->set_name('Held origin review');$p->set_regular_price(100);$p->save();$c=wp_insert_comment(array('comment_post_ID'=>$p->get_id(),'user_id'=>$u,'comment_type'=>'review','comment_approved'=>1,'comment_content'=>'Synthetic'));do_action('comment_post',$c,1,get_comment($c,ARRAY_A));YOWCL_Free_Core::level_bonus($u,'subscriber');
foreach(array('Points_Reward','Points_Deduct','Level_Update') as $id){$class='YOWCL_WC_Email_Loyalty_'.$id;$mail=new $class();loyf_assert(!$mail->is_enabled(),'Held native mail');if('Level_Update'===$id){$mail->trigger($u,'subscriber',29);}else{$mail->trigger($u,17,50);}}
loyf_equal(0,$sent,'Held sends no native mail');loyf_equal($rows,$wpdb->get_results("SELECT * FROM {$wpdb->prefix}yo_loyalty_points_log ORDER BY id",ARRAY_A),'Held admits no fresh value');loyf_equal('',get_user_meta($u,'user_points',true),'No held reward balance');
wp_set_current_user($u);WC()->initialize_session();WC()->initialize_cart();WC()->cart->add_to_cart($p->get_id());update_user_meta($u,'user_points',100);$session=WC()->session->get_session_data();try{YOWCL_Free_Cart::apply('20');throw new RuntimeException('Held redemption admitted');}catch(DomainException $e){}loyf_equal($session,WC()->session->get_session_data(),'No new held selection');
$persistence['meta']=$wpdb->get_results("SELECT * FROM {$wpdb->usermeta} ORDER BY umeta_id",ARRAY_A);file_put_contents(getenv('LOYF13_SNAPSHOT').'.persistence',serialize($persistence));
echo "Installed Premium-origin Free hold PASS: raw canonical/license wrappers; eight absent witnesses; native positive hooks/mail triggers and new selection denied. Simulated entitlement.\n";
