<?php
require __DIR__ . '/assertions.php';
global $wpdb;
$names=array('loyalty_extra_points_rules','loyalty_extra_reviews_gamification_rules','loyalty_points_earning_rules',YOWCL_Free_First_Purchase::RULES,YOWCL_Free_First_Purchase::WITNESS);
$saved=array();foreach($names as$name){$saved[$name]=get_option($name,null);}
$actor=get_current_user_id();wp_set_current_user(1);
function loyf9_user($name){$id=wp_insert_user(array('user_login'=>'first_'.$name,'user_email'=>'first_'.$name.'@example.invalid','user_pass'=>'disposable-only','role'=>'customer'));loyf_assert(!is_wp_error($id),'First customer');return(int)$id;}
function loyf9_order($user,$date=null,$status='pending'){$skip=static function(){return true;};add_filter('yowcl_skip_points_for_order',$skip,PHP_INT_MAX);try{$o=wc_create_order(array('customer_id'=>$user));if(null!==$date){$o->set_date_created($date);}$o->set_status($status);$o->save();return$o;}finally{remove_filter('yowcl_skip_points_for_order',$skip,PHP_INT_MAX);}}
function loyf9_row($user){return YOWCL_Points_Transaction::find('reward:first_purchase:'.$user);}
function loyf9_none($user,$label){loyf_equal(null,loyf9_row($user),$label);loyf_balance($user,0,0,$label);}
function loyf9_retry($order){$ids=as_get_scheduled_actions(array('hook'=>YOWCL_Advanced_Rewards::ORDER_HOOK,'group'=>YOWCL_Advanced_Rewards::GROUP,'args'=>array($order->get_id(),'first_purchase'),'status'=>'pending','per_page'=>10),'ids');loyf_assert(count($ids)>0,'Retained First Purchase AS owner');foreach($ids as$id){ActionScheduler::runner()->process_action($id,'LOYF9');}}
function loyf9_save($points,$enabled=true){$_POST=array('extra_points_settings_nonce'=>wp_create_nonce('save_extra_points_settings_action'),'loyalty_extra_first_purchase_points'=>(string)$points);if($enabled){$_POST['loyalty_extra_first_purchase_enabled']='yes';}(new YOSWC_Loyalty_Settings_Extra_Points())->save_extra_points_settings();$_POST=array();}
try{
 update_option('loyalty_extra_points_rules',array('signup_enabled'=>'no','login_enabled'=>'no','review_enabled'=>'no'));update_option('loyalty_extra_reviews_gamification_rules',array('levelup_enabled'=>'no'));update_option('loyalty_points_earning_rules',array());
 // No boot witness for dormant Premium-shaped data; explicit authorized native form preserves unknown fields/wrapper.
 $unknown=array('milestone_enabled'=>'yes','milestone_points'=>array(10=>50),'custom'=>(object)array('nested'=>array('keep')));
 update_option(YOWCL_Free_First_Purchase::RULES,serialize(array_merge($unknown,array('first_purchase_enabled'=>'yes','first_purchase_points'=>'25'))));delete_option(YOWCL_Free_First_Purchase::WITNESS);
 $raw=YOWCL_Free_Migrations::read(YOWCL_Free_First_Purchase::RULES);$u=loyf9_user('dormant');$o=loyf9_order($u);$o->update_status('processing');loyf9_none($u,'Dormant no cutoff held');loyf_equal(null,get_option(YOWCL_Free_First_Purchase::WITNESS,null),'No boot cutoff');loyf_equal($raw,YOWCL_Free_Migrations::read(YOWCL_Free_First_Purchase::RULES),'Dormant untouched');ob_start();YOWCL_Free_First_Purchase::notices();$notice=ob_get_clean();loyf_assert(false!==strpos($notice,'Explicitly save'),'Bounded admin diagnostic');
 loyf9_save(25);$epoch=YOWCL_Free_First_Purchase::configuration()['epoch'];loyf_assert(YOWCL_Free_First_Purchase::configuration()['ready'],'Explicit save establishes cutoff');$rules=maybe_unserialize(get_option(YOWCL_Free_First_Purchase::RULES));foreach($unknown as$key=>$value){loyf_equal(serialize($value),serialize($rules[$key]),'Unknown fields preserved');}loyf_assert(is_string(get_option(YOWCL_Free_First_Purchase::RULES)),'Legacy wrapper retained');
 // Whole point validation, atomic rollback of each option write, and same positive epoch.
 foreach(array('-1','1.5','1e2','100000000',array(1))as$bad){try{YOWCL_Free_First_Purchase::save(true,$bad);throw new RuntimeException('Invalid accepted');}catch(DomainException$e){}}
 foreach(array(YOWCL_Free_First_Purchase::RULES,YOWCL_Free_First_Purchase::WITNESS)as$target){$before=array(YOWCL_Free_Migrations::read(YOWCL_Free_First_Purchase::RULES),YOWCL_Free_Migrations::read(YOWCL_Free_First_Purchase::WITNESS));$fault=function($step,$key)use($target){if('first_purchase_settings_write'===$step&&$target===$key){throw new RuntimeException('First settings partial failure');}};add_action('yowcl_reward_test_checkpoint',$fault,10,2);try{YOWCL_Free_First_Purchase::save(true,99);throw new DomainException('Fault missing');}catch(RuntimeException$e){loyf_equal('First settings partial failure',$e->getMessage(),'Injected partial save');}finally{remove_action('yowcl_reward_test_checkpoint',$fault,10);}loyf_equal($before,array(YOWCL_Free_Migrations::read(YOWCL_Free_First_Purchase::RULES),YOWCL_Free_Migrations::read(YOWCL_Free_First_Purchase::WITNESS)),'Atomic settings pair rollback');}
 YOWCL_Free_First_Purchase::save(true,26);loyf_equal($epoch['cutoff'],YOWCL_Free_First_Purchase::configuration()['epoch']['cutoff'],'Positive edit keeps epoch');YOWCL_Free_First_Purchase::save(true,25);
 $cutoff=$epoch['cutoff'];
 foreach(array('pending','checkout-draft')as$status){$u=loyf9_user('pre_'.$status);$o=loyf9_order($u,$cutoff-1,$status);$o->update_status('processing');do_action('woocommerce_payment_complete',$o->get_id());loyf9_none($u,'Pre-enable '.$status.' denied');}
 $u=loyf9_user('tie');$o=loyf9_order($u,$cutoff);$o->update_status('processing');loyf9_none($u,'Equal cutoff denied');$missing=clone$o;$missing->set_date_created(null);loyf_equal(null,YOWCL_Free_First_Purchase::admission($missing),'Missing date denied');
 // Real newly created order (strict second-resolution cutoff), normal registered status/payment callbacks.
 while(time()<=$cutoff){usleep(100000);} $u=loyf9_user('fresh');$o=loyf9_order($u);$o->update_status('processing');loyf_balance($u,25,25,'Fresh first award');$row=loyf9_row($u);loyf_equal('first_purchase_reward',$row['action'],'Canonical action');loyf_equal($o->get_id(),(int)$row['order_id'],'Winning order');$o->update_status('completed');do_action('woocommerce_payment_complete',$o->get_id());loyf_equal(1,count(loyf_rows($u)),'Replay one row');
 $second=loyf9_order($u);$second->update_status('processing');loyf_balance($u,25,25,'Second no award');loyf_equal('yes',wc_get_order($second->get_id())->get_meta('_yowcl_first_purchase_awarded'),'Losing receipt converges');
 // Historical qualifying order, legacy user/order evidence, ownership/roles and compatible skips.
 $u=loyf9_user('history');$past=loyf9_order($u,$cutoff-3600,'completed');$o=loyf9_order($u);$o->update_status('processing');loyf9_none($u,'History before cutoff still suppresses');
 foreach(array('user','order','guest','role','child','filter')as$case){$u='guest'===$case?0:loyf9_user($case);$o=loyf9_order($u);if('user'===$case){update_user_meta($u,'first_purchase_rewarded',1);}if('order'===$case){$o->update_meta_data('_yowcl_first_purchase_awarded','yes');}if('role'===$case){get_userdata($u)->set_role('subscriber');}if('child'===$case){$o->set_parent_id($past->get_id());}$o->save();$skip=function($skip,$order)use($o){return$skip||$order->get_id()===$o->get_id();};if('filter'===$case){add_filter('yowcl_skip_points_for_order',$skip,10,2);}$o->update_status('processing');if('filter'===$case){remove_filter('yowcl_skip_points_for_order',$skip,10);}loyf9_none($u,'Excluded '.$case);}
 // A real SQL query error is retained recovery, never empty history. Malformed pagination also denies.
 $u=loyf9_user('query');$o=loyf9_order($u,null,'processing');$hpos=Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled();$failed=false;$fault=function($sql)use(&$failed,$hpos,$wpdb){if(!$failed&&0===strpos(ltrim($sql),'SELECT')&&false!==strpos($sql,$hpos?$wpdb->prefix.'wc_orders':$wpdb->posts)&&false!==strpos($sql,$hpos?'customer_id':'post_type')){$failed=true;return'SELECT * FROM loyf9_intentionally_missing';}return$sql;};$old=$wpdb->suppress_errors(true);add_filter('query',$fault,1);(new YOWCL_Extra_Points_First_Purchase(false))->maybe_award_on_order($o);remove_filter('query',$fault,1);$wpdb->suppress_errors($old);$wpdb->last_error='';loyf_assert($failed,'Native history SELECT fault reached');loyf9_none($u,'Failed history denied');loyf9_retry($o);loyf_balance($u,25,25,'History retry recovered');try{YOWCL_Advanced_Rewards::pagination(array('orders'=>array(),'total'=>1,'max_num_pages'=>1));throw new DomainException('Malformed accepted');}catch(RuntimeException$e){loyf_equal('advanced_reward_pagination_invalid',$e->getMessage(),'Malformed pagination denied');}
 // Actual native user ownership contention retains original terms after settings drift.
 $u=loyf9_user('lock');$o=loyf9_order($u,time()+1);$lock=YOWCL_Points_Lock::acquire($u);loyf_assert(is_array($lock),'Actual user lock held');try{$o->update_status('processing');loyf9_none($u,'Native user contention holds value');YOWCL_Free_First_Purchase::save(true,70);}finally{YOWCL_Points_Lock::release($lock);}loyf9_retry($o);loyf_balance($u,25,25,'Contended retry original terms');YOWCL_Free_First_Purchase::save(true,25);
 // Freeze then defer before transaction; re-enable does not replace accepted terms. Terminal beats uncommitted receipt.
 foreach(array('recover','terminal')as$case){$u=loyf9_user($case);$o=loyf9_order($u,time()+1);$key='reward:first_purchase:'.$u;$fault=function($step,$event)use($key){if('prepared'===$step&&$event===$key){throw new RuntimeException('First deferred');}};add_action('yowcl_reward_test_checkpoint',$fault,10,2);$o->update_status('processing');remove_action('yowcl_reward_test_checkpoint',$fault,10);loyf9_none($u,'Frozen deferred');$receipt=wc_get_order($o->get_id())->get_meta('_yowcl_advanced_terms_first_purchase');loyf_equal(25,$receipt['events'][0]['points'],'Frozen original points');YOWCL_Free_First_Purchase::save(false,25);YOWCL_Free_First_Purchase::save(true,80);if('terminal'===$case){$o->update_status('cancelled');}loyf9_retry($o);if('terminal'===$case){loyf9_none($u,'Terminal before commit');}else{loyf_balance($u,25,25,'Accepted recovery across re-enable');}YOWCL_Free_First_Purchase::save(true,25);}
 // Marker recovery goes ahead of current disabled settings and terminal state; committed bonus has no new clawback.
 $u=loyf9_user('markers');$o=loyf9_order($u,time()+1);$o->update_status('processing');$before=loyf_rows($u);delete_user_meta($u,'first_purchase_rewarded');$o=wc_get_order($o->get_id());$o->delete_meta_data('_yowcl_first_purchase_awarded');$o->delete_meta_data('_yowcl_advanced_terms_first_purchase');$o->save();YOWCL_Free_First_Purchase::save(false,25);$o->update_status('cancelled');do_action('woocommerce_payment_complete',$o->get_id());loyf_equal($before,loyf_rows($u),'Committed repair appends nothing');loyf_balance($u,25,25,'Committed bonus retained');loyf_equal(1,(int)get_user_meta($u,'first_purchase_rewarded',true),'User marker restored');loyf_equal('yes',wc_get_order($o->get_id())->get_meta('_yowcl_first_purchase_awarded'),'Winner restored');
 foreach(array('disabled','zero')as$case){YOWCL_Free_First_Purchase::save('zero'===$case,'zero'===$case?0:25);$u=loyf9_user($case);$o=loyf9_order($u,time()+1);$o->update_status('processing');loyf9_none($u,$case.' held');loyf_equal(false,YOWCL_Free_First_Purchase::configuration()['epoch']['enabled'],'Epoch closed');}
 $u=loyf9_user('old_epoch');$o=loyf9_order($u,time()-1);YOWCL_Free_First_Purchase::save(true,25);$new=YOWCL_Free_First_Purchase::configuration()['epoch'];loyf_assert($new['cutoff']>$cutoff,'New epoch after zero');$o->update_status('processing');loyf9_none($u,'Old epoch order denied');
 // Native two-process user-wide race. Both candidate statuses exist before callbacks, ID resolves creation ties.
 $u=loyf9_user('race');$a=loyf9_order($u,time()+1,'processing');$b=loyf9_order($u,$a->get_date_created()->getTimestamp(),'processing');$barrier=tempnam(sys_get_temp_dir(),'loyf9-race-');unlink($barrier);$workers=array();foreach(array($a,$b)as$i=>$order){$env=getenv();$env['LOYF9_ORDER']=(string)$order->get_id();$env['LOYF9_BARRIER']=$barrier;$env['LOYF9_INDEX']=(string)$i;$pipes=array();$p=proc_open(array(PHP_BINARY,getenv('LOYF_WP_CLI_PHAR'),'--path='.ABSPATH,'eval-file',__DIR__.'/first-purchase-worker.php','--quiet'),array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('pipe','w')),$pipes,null,$env);loyf_assert(is_resource($p),'First native worker');fclose($pipes[0]);$workers[]=array($p,$pipes);}try{foreach($workers as$worker){$out=stream_get_contents($worker[1][1]);$err=stream_get_contents($worker[1][2]);fclose($worker[1][1]);fclose($worker[1][2]);loyf_equal(0,proc_close($worker[0]),'First race '.$out.$err);}}finally{foreach(array('.0','.1')as$suffix){if(file_exists($barrier.$suffix)){unlink($barrier.$suffix);}}}wp_cache_delete($u,'user_meta');loyf_balance($u,25,25,'Race one winner');loyf_equal(1,count(loyf_rows($u)),'Race one row');foreach(array($a,$b)as$order){(new YOWCL_Extra_Points_First_Purchase(false))->maybe_award_on_order($order);loyf_equal('yes',wc_get_order($order->get_id())->get_meta('_yowcl_first_purchase_awarded'),'Race projections converge');}
 $identity_rows=$wpdb->get_results("SELECT * FROM ".YOWCL_Points_Log::table_name()." WHERE action='first_purchase_reward' ORDER BY id",ARRAY_A);require __DIR__.'/upstream-replay.php';
 echo 'Native First Purchase '.getenv('LOYF_STORAGE').' PASS Woo'.WC_VERSION.' WP'.get_bloginfo('version')."\n";
}finally{wp_set_current_user($actor);$_POST=array();foreach($saved as$name=>$value){if(null===$value){delete_option($name);}else{update_option($name,$value);}}}
