<?php
/** Native LOYF-27 protocol and AS delivery; disposable sites only. */
require_once __DIR__.'/assertions.php';
if (!defined('LOYF_RUNTIME_DISPOSABLE')) { throw new RuntimeException('Disposable required'); }
global $wpdb;
if ('replace'===($args[0]??'')) { if(isset($args[4])){add_filter('query',static function($sql)use($args){static $paused=false;if(!$paused&&strpos($sql,"option_name = 'loyf_migration_signup_v1'")!==false){$paused=true;file_put_contents($args[4],'locked');usleep(500000);}return $sql;},PHP_INT_MAX);} wp_set_current_user(1);echo YOWCL_Free_Migrations::replace_pending($args[1],$args[2],$args[3],wp_create_nonce('loyf_replace_'.$args[1]));return; }
if ('worker'===($args[0]??'')) {
    if ('gate'===($args[2]??'')) { add_filter('query',static function($sql)use($args){static $paused=false;if(!$paused&&strpos($sql,"option_name = 'loyf_migration_signup_v1_background'")!==false){$paused=true;file_put_contents($args[3],'locked');usleep(500000);}return $sql;},PHP_INT_MAX); }
    if ('abort'===($args[2]??'')) { add_filter('query',static function($sql){if(strpos($sql,"'loyf_migration_signup_v1',")!==false && 0===strpos($sql,'INSERT INTO ')){exit(9);}return $sql;},PHP_INT_MAX); }
    ActionScheduler_QueueRunner::instance()->process_action((int)$args[1],'LOYF-27 independent worker');return;
}
wp_set_current_user(1);
$targets=array('signup'=>'loyalty_extra_points_rules','login'=>'loyalty_extra_points_rules','review'=>'loyalty_extra_reviews_gamification_rules','levelup'=>'loyalty_extra_reviews_gamification_rules','redemption'=>'loyalty_points_using_rules','email_reward'=>'woocommerce_yowcl_loyalty_points_reward_settings','email_deduct'=>'woocommerce_yowcl_loyalty_points_deduct_settings','email_level'=>'woocommerce_yowcl_loyalty_level_update_settings');
$names=array_merge(array_values($targets),array('loyalty_extra_levelup_points_rules','loyalty_notification_email','loyalty_points_using_point','woocommerce_currency'));
foreach(YOWCL_Free_Migrations::features() as $f){foreach(array('','_before','_resolution','_background','_supersession') as $s){$names[]=YOWCL_Free_Migrations::witness($f).$s;}}
$names=array_unique($names);$saved=array();foreach($names as $n){$saved[$n]=$wpdb->get_row($wpdb->prepare("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",$n),ARRAY_A);}
$business=static function()use($wpdb){return array($wpdb->get_results("SELECT * FROM {$wpdb->usermeta} WHERE meta_key IN ('user_points','user_earning_points') ORDER BY umeta_id",ARRAY_A),$wpdb->get_results("SELECT * FROM {$wpdb->prefix}yo_loyalty_points_log ORDER BY id",ARRAY_A),get_option($wpdb->prefix.'user_roles'));};
$before=$business();$children=array();$actor=0;$notice_exists=metadata_exists('user',1,'loyf_migration_notice_dismissed');$notice_before=get_user_meta(1,'loyf_migration_notice_dismissed',true);
$store=static function($name,$raw,$autoload='no')use($wpdb){$wpdb->query($wpdb->prepare("INSERT INTO {$wpdb->options}(option_name,option_value,autoload) VALUES(%s,%s,%s) ON DUPLICATE KEY UPDATE option_value=VALUES(option_value),autoload=VALUES(autoload)",$name,$raw,$autoload));wp_cache_delete($name,'options');wp_cache_delete('alloptions','options');wp_cache_delete('notoptions','options');};
$reset=static function()use($store){
    as_unschedule_all_actions(YOWCL_Free_Migrations::HOOK,null,YOWCL_Free_Migrations::GROUP);
    foreach(YOWCL_Free_Migrations::features() as $f){foreach(array('','_before','_resolution','_background','_supersession') as $s){delete_option(YOWCL_Free_Migrations::witness($f).$s);}}
    $store('loyalty_extra_points_rules',serialize(serialize(array('signup_points'=>'15','signup_enabled'=>'no','login_points'=>'7','login_enabled'=>'yes','review_points'=>'25','unknown'=>(object)array('keep'=>'009')))),'yes');
    $store('loyalty_extra_reviews_gamification_rules',serialize(array('review_points'=>'30','review_enabled'=>'yes','levelup_enabled'=>'yes','levelup_points'=>array('customer'=>array('awarded'=>'30')),'unknown'=>'007')));
    $store('loyalty_extra_levelup_points_rules',serialize(array('customer'=>array('awarded'=>'50'))));
    $store('loyalty_notification_email',serialize(array('points_update'=>false,'level_update'=>true)));
    $store('loyalty_points_using_rules',serialize(serialize(array('points'=>'10','amount'=>'0.7010','min_points'=>'','max_points'=>'','min_cart'=>'','unknown'=>'003'))));
    $store('loyalty_points_using_point','yes');
    foreach(array('points_reward','points_deduct','level_update') as $id){$store('woocommerce_yowcl_loyalty_'.$id.'_settings',serialize(array('enabled'=>'yes','subject'=>'Retain native subject','heading'=>'Retain native heading')));}
};
$choices=static function($modes){$out=array();foreach($modes as $f=>$mode){$spec=YOWCL_Free_Migrations::preview($f,$mode);$out[$f]=array('mode'=>$mode,'fingerprint'=>hash('sha256',serialize($spec)));}return $out;};
$admit=static function($modes)use($choices){$vector=$choices($modes);$batch=wp_generate_uuid4();YOWCL_Free_Migrations::admit($vector,$batch,wp_create_nonce('loyf_confirm_migrations'));return array($vector,$batch);};
$drain=static function(){for($i=0;$i<4;$i++){$ids=as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'group'=>YOWCL_Free_Migrations::GROUP,'status'=>'pending','per_page'=>50),'ids');if(!$ids){return;}foreach($ids as$id){ActionScheduler_QueueRunner::instance()->process_action($id,'LOYF-27 native replay');}}};
$direct=static function($feature,$mode,$expected='confirmed'){$spec=YOWCL_Free_Migrations::preview($feature,$mode);$_SERVER['REQUEST_METHOD']='POST';$_POST=array('feature'=>$feature,'mode'=>$mode,'fingerprint'=>YOWCL_Free_Migrations::resolution_fingerprint($feature,$spec),'_wpnonce'=>wp_create_nonce('loyf_resolve_'.$feature));$redirect=static function($url){throw new RuntimeException('redirect:'.$url);};add_filter('wp_redirect',$redirect,0);try{do_action('admin_post_loyf_resolve_migration');throw new LogicException('No native direct handler');}catch(RuntimeException $e){loyf_assert(strpos($e->getMessage(),'result='.$expected)!==false,'Fresh direct POST reports '.$expected);}finally{remove_filter('wp_redirect',$redirect,0);$_POST=array();}};
$replacement=static function($feature,$mode,$expected='confirmed') {
    $proposal=YOWCL_Free_Migrations::replacement_preview($feature,$mode);$_SERVER['REQUEST_METHOD']='POST';$_POST=array('feature'=>$feature,'mode'=>$mode,'fingerprint'=>$proposal['fingerprint'],'_wpnonce'=>wp_create_nonce('loyf_replace_'.$feature));$redirect=static function($url){throw new RuntimeException('redirect:'.$url);};add_filter('wp_redirect',$redirect,0);
    try{do_action('admin_post_loyf_replace_migration');throw new LogicException('Missing replacement POST');}catch(RuntimeException $e){loyf_assert(strpos($e->getMessage(),'result='.$expected)!==false,'Native replacement PRG '.$expected);}finally{remove_filter('wp_redirect',$redirect,0);$_POST=array();}
};
$edit=static function($name,$patch)use($wpdb,$store){$row=$wpdb->get_row($wpdb->prepare("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",$name),ARRAY_A);$v=maybe_unserialize(maybe_unserialize($row['option_value']));$v=array_replace($v,$patch);$raw=is_string(maybe_unserialize($row['option_value']))?serialize(serialize($v)):serialize($v);$store($name,$raw,$row['autoload']);};
$deny=static function($callback,$code){try{$callback();throw new LogicException('Unexpected admission');}catch(RuntimeException $e){loyf_equal($code,$e->getMessage(),'Native refusal');}};
$cache_fault=static function($key) {
    return new class($key) extends WP_Object_Cache {
        public $armed=false;private $fault_key;
        public function __construct($key){parent::__construct();$this->fault_key=$key;}
        public function delete($key,$group='default',$deprecated=false){if($this->armed&&$this->fault_key===$key){$this->armed=false;throw new RuntimeException('loyf27_cache_response_failure');}return parent::delete($key,$group,$deprecated);}
    };
};
try {
    $reset();YOWCL_Free_Migrations::schedule();loyf_equal('needs_attention',YOWCL_Free_Migrations::status()['state'],'Uncaptured cannot queue');loyf_equal(array(),as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids'),'No endless ambiguous queue');
    ob_start();YOWCL_Free_Migrations::render_review();$html=ob_get_clean();loyf_assert(strpos($html,'50')!==false&&strpos($html,'30')!==false&&strpos($html,'0.7')!==false,'Visible reviewed role and currency differences');
    // GET-reviewed redemption context cannot be replaced with terms observed only at POST.
    $currency=get_option('woocommerce_currency');$vector=$choices(array('redemption'=>'canonical'));$store('woocommerce_currency','EUR'===$currency?'USD':'EUR');
    $deny(static function()use($vector){YOWCL_Free_Migrations::admit($vector,wp_generate_uuid4(),wp_create_nonce('loyf_confirm_migrations'));},'migration_resolution_stale');$store('woocommerce_currency',$currency);
    $vector=$choices(array('redemption'=>'canonical'));$store('loyalty_points_using_point','no');
    $deny(static function()use($vector){YOWCL_Free_Migrations::admit($vector,wp_generate_uuid4(),wp_create_nonce('loyf_confirm_migrations'));},'migration_resolution_stale');$store('loyalty_points_using_point','yes');
    loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_redemption_v1_resolution'),'GET context drift admits no intent');
    // A durable COMMIT with a lost response is unknown, never a definitive rejection.
    $vector=$choices(array('signup'=>'canonical','login'=>'canonical'));$batch=wp_generate_uuid4();$committed=false;
    $fault=static function($sql)use($wpdb,&$committed){if('COMMIT'===$sql&&!$committed){mysqli_query($wpdb->dbh,'COMMIT');$committed=true;return 'SELECT * FROM loyf27_lost_commit_response';}return $sql;};
    $_SERVER['REQUEST_METHOD']='POST';$_POST=array('choices'=>$vector,'batch'=>$batch,'_wpnonce'=>wp_create_nonce('loyf_confirm_migrations'));
    $redirect=static function($url){throw new RuntimeException('redirect:'.$url);};add_filter('wp_redirect',$redirect,0);add_filter('query',$fault,PHP_INT_MAX);
    try{do_action('admin_post_loyf_confirm_migrations');throw new LogicException('No native POST handler');}catch(RuntimeException $e){loyf_assert(strpos($e->getMessage(),'batch_result=unknown')!==false,'Lost COMMIT response is honestly unknown');}finally{remove_filter('query',$fault,PHP_INT_MAX);remove_filter('wp_redirect',$redirect,0);$_POST=array();}
    foreach(array('signup','login') as$f){$c=get_option(YOWCL_Free_Migrations::witness($f).'_resolution')['consent'];loyf_equal($batch,$c['batch'],'Whole committed vector persists with exact batch identity');}
    YOWCL_Free_Migrations::admit($vector,$batch,wp_create_nonce('loyf_confirm_migrations'));$drain();loyf_assert(YOWCL_Free_Migrations::ready('signup')&&YOWCL_Free_Migrations::ready('login'),'Exact duplicate recovers unknown admission without extra choices');$reset();
    // Admission cleanup cannot turn a durable vector into a definitive rejection, even after a lost COMMIT response.
    foreach(array('rollback','committed','lost-response') as $outcome) {
        $reset();$vector=$choices(array('signup'=>'disable','login'=>'disable'));$batch=wp_generate_uuid4();$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$cache=$GLOBALS['wp_object_cache'];$fault_cache=$cache_fault('loyalty_extra_points_rules');$GLOBALS['wp_object_cache']=$fault_cache;
        $fault=static function($sql)use($wpdb,$outcome,$fault_cache){
            if('rollback'===$outcome&&0===strpos($sql,'INSERT INTO '.$wpdb->options)&&strpos($sql,"'loyf_migration_login_v1_resolution'")!==false){$fault_cache->armed=true;return 'SELECT * FROM loyf27_admission_cleanup_rollback';}
            if('COMMIT'===$sql){$fault_cache->armed=true;if('lost-response'===$outcome){mysqli_query($wpdb->dbh,'COMMIT');return 'SELECT * FROM loyf27_admission_cleanup_response';}}
            return $sql;
        };
        $_SERVER['REQUEST_METHOD']='POST';$_POST=array('choices'=>$vector,'batch'=>$batch,'_wpnonce'=>wp_create_nonce('loyf_confirm_migrations'));$redirect=static function($url){throw new RuntimeException('redirect:'.$url);};add_filter('query',$fault,PHP_INT_MAX);add_filter('wp_redirect',$redirect,0);
        try{do_action('admin_post_loyf_confirm_migrations');throw new LogicException('No admission POST');}catch(RuntimeException $e){loyf_assert(strpos($e->getMessage(),'batch_result='.('rollback'===$outcome?'unconfirmed':'unknown'))!==false,'Admission cleanup reports actual authority boundary '.$outcome);}finally{remove_filter('query',$fault,PHP_INT_MAX);remove_filter('wp_redirect',$redirect,0);$GLOBALS['wp_object_cache']=$cache;wp_cache_flush();$_POST=array();}
        loyf_assert(!$fault_cache->armed,'Actual admission cleanup exception exercised');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Admission never completes targets');
        foreach(array('signup','login') as $f){$pending=YOWCL_Free_Migrations::read(YOWCL_Free_Migrations::witness($f).'_resolution');loyf_equal('rollback'!==$outcome,null!==$pending,'Atomic admission storage after cleanup');loyf_assert(!YOWCL_Free_Migrations::ready($f),'Admission is not completion');if('rollback'!==$outcome){loyf_equal($batch,get_option(YOWCL_Free_Migrations::witness($f).'_resolution')['consent']['batch'],'Committed vector retains reviewed identity');}}
        if('rollback'!==$outcome){YOWCL_Free_Migrations::admit($vector,$batch,wp_create_nonce('loyf_confirm_migrations'));$drain();loyf_assert(YOWCL_Free_Migrations::ready('signup')&&YOWCL_Free_Migrations::ready('login'),'Same-identity retry recovers unknown admission');loyf_equal(0,YOWCL_Free_Core::extra('signup'),'Reviewed disable is effective');}else{YOWCL_Free_Migrations::schedule();loyf_equal(array(),as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids'),'Failed admission has no worker authority');}
    }
    $reset();
    // Genuine aggregate POST through its registered endpoint; redirect interception avoids fixture exit.
    $vector=$choices(array('signup'=>'canonical','login'=>'disable','review'=>'legacy','levelup'=>'legacy','redemption'=>'canonical','email_reward'=>'legacy','email_deduct'=>'canonical','email_level'=>'disable'));$batch=wp_generate_uuid4();
    $_SERVER['REQUEST_METHOD']='POST';$_POST=array('choices'=>$vector,'batch'=>$batch,'_wpnonce'=>wp_create_nonce('loyf_confirm_migrations'));
    $redirect=static function($url){throw new RuntimeException('redirect:'.$url);};add_filter('wp_redirect',$redirect,0);
    try{do_action('admin_post_loyf_confirm_migrations');throw new LogicException('No native POST handler');}catch(RuntimeException $e){loyf_assert(strpos($e->getMessage(),'batch_result=admitted')!==false,'Native one POST vector admitted');}finally{remove_filter('wp_redirect',$redirect,0);$_POST=array();}
    foreach(YOWCL_Free_Migrations::features() as $f){loyf_assert(!YOWCL_Free_Migrations::ready($f),'Admission is not completion');loyf_assert(get_option(YOWCL_Free_Migrations::witness($f).'_resolution')!==false,'Entire vector recorded');$c=get_option(YOWCL_Free_Migrations::witness($f).'_resolution')['consent'];loyf_equal(86400,$c['expires']-$c['issued'],'Consent bounded to24h');}
    $raw=YOWCL_Free_Migrations::read('loyalty_points_using_rules');YOWCL_Free_Migrations::admit($vector,$batch,wp_create_nonce('loyf_confirm_migrations'));
    loyf_equal(8,count(as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids')),'Duplicate submit deduplicates');
    $drain();loyf_equal('completed',YOWCL_Free_Migrations::status()['state'],'Eight independently verified witnesses');
    loyf_equal($raw,YOWCL_Free_Migrations::read('loyalty_points_using_rules'),'Keep current exact raw fractional wrapper');loyf_equal(25,YOWCL_Free_Core::extra('review'),'Selected legacy review');loyf_equal('50',YOWCL_Free_Core::level_rules()['customer']['awarded'],'Selected role50');
    $confirmed=$business();$drain();YOWCL_Free_Migrations::admit($vector,$batch,wp_create_nonce('loyf_confirm_migrations'));loyf_equal($confirmed,$business(),'Replay creates no economics');
    // Native AJAX dismissal guards and preference readback; none of these authorizes migration.
    $reset();delete_user_meta(1,'loyf_migration_notice_dismissed');require_once ABSPATH.'wp-admin/includes/class-wp-screen.php';require_once ABSPATH.'wp-admin/includes/screen.php';set_current_screen('dashboard');ob_start();YOWCL_Free_Migrations::notices();$notice=ob_get_clean();preg_match('/data-token="([a-f0-9]{64})"/',$notice,$match);loyf_assert(isset($match[1]),'Authorized notice token');
    $die=static function(){return static function(){throw new RuntimeException('loyf27-json-exit');};};add_filter('wp_die_ajax_handler',$die,PHP_INT_MAX);add_filter('wp_die_handler',$die,PHP_INT_MAX);
    $json=static function($post){$_SERVER['REQUEST_METHOD']='POST';$_POST=$post;ob_start();try{do_action('wp_ajax_loyf_dismiss_migration');}catch(RuntimeException $e){loyf_equal('loyf27-json-exit',$e->getMessage(),'Native JSON termination');}finally{$_POST=array();}return json_decode(ob_get_clean(),true);};
    try{loyf_equal(false,$json(array('_wpnonce'=>'invalid','token'=>$match[1]))['success'],'Dismiss denied nonce');$denied_actor=wp_insert_user(array('user_login'=>'loyf27_denied_'.substr(wp_generate_uuid4(),0,8),'user_pass'=>'disposable-only','role'=>'subscriber'));wp_set_current_user($denied_actor);loyf_equal(false,$json(array('_wpnonce'=>wp_create_nonce('loyf_dismiss_migration'),'token'=>$match[1]))['success'],'Dismiss denied capability');wp_set_current_user(1);require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($denied_actor);loyf_equal(false,$json(array('_wpnonce'=>wp_create_nonce('loyf_dismiss_migration'),'token'=>str_repeat('0',64)))['success'],'Dismiss denied stale state');loyf_equal(true,$json(array('_wpnonce'=>wp_create_nonce('loyf_dismiss_migration'),'token'=>$match[1]))['success'],'Guarded persistent dismissal');loyf_equal($match[1],get_user_meta(1,'loyf_migration_notice_dismissed',true),'Dismiss preference persisted');foreach(YOWCL_Free_Migrations::features()as$f){loyf_assert(!YOWCL_Free_Migrations::ready($f),'Dismiss never creates witness');}}finally{remove_filter('wp_die_ajax_handler',$die,PHP_INT_MAX);remove_filter('wp_die_handler',$die,PHP_INT_MAX);}
    // Atomic admission rollback on a real failed second intent INSERT.
    $reset();$vector=$choices(array('signup'=>'canonical','login'=>'canonical'));$fault=static function($sql)use($wpdb){return strpos($sql,'INSERT INTO '.$wpdb->options)!==false&&strpos($sql,"'loyf_migration_login_v1_resolution'")!==false?'SELECT * FROM loyf27_no_admission_table':$sql;};
    add_filter('query',$fault,PHP_INT_MAX);try{$deny(static function()use($vector){YOWCL_Free_Migrations::admit($vector,wp_generate_uuid4(),wp_create_nonce('loyf_confirm_migrations'));},'migration_write_failed');}finally{remove_filter('query',$fault,PHP_INT_MAX);}
    foreach(array('signup','login')as$f){loyf_equal(null,YOWCL_Free_Migrations::read(YOWCL_Free_Migrations::witness($f).'_resolution'),'No partial executable intent');}
    loyf_equal(array(),as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids'),'Rollback never queued');
    // Stale whole vector denies admission before writing any intent.
    $reset();$vector=$choices(array('signup'=>'canonical','login'=>'canonical'));$v=maybe_unserialize(maybe_unserialize(YOWCL_Free_Migrations::read('loyalty_extra_points_rules')));$v['login_points']='8';$store('loyalty_extra_points_rules',serialize(serialize($v)),'yes');
    $deny(static function()use($vector){YOWCL_Free_Migrations::admit($vector,wp_generate_uuid4(),wp_create_nonce('loyf_confirm_migrations'));},'migration_resolution_stale');loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Stale vector has no early admission');
    // Later owned edit stops only that feature; independent sibling converges.
    $reset();$admit(array('signup'=>'canonical','login'=>'disable'));$v=maybe_unserialize(maybe_unserialize(YOWCL_Free_Migrations::read('loyalty_extra_points_rules')));$v['signup_points']='99';$store('loyalty_extra_points_rules',serialize(serialize($v)),'yes');$drain();
    loyf_assert(!YOWCL_Free_Migrations::ready('signup')&&YOWCL_Free_Migrations::ready('login'),'Partial execution truth');loyf_equal('99',maybe_unserialize(maybe_unserialize(YOWCL_Free_Migrations::read('loyalty_extra_points_rules')))['signup_points'],'Merchant edit wins');
    // Expiry and revocation cannot continue; old pending intents cannot enter AS.
    $reset();$admit(array('signup'=>'canonical'));$spec=get_option('loyf_migration_signup_v1_resolution');$spec['consent']['issued']=time()-86401;$spec['consent']['expires']=time()-1;$store('loyf_migration_signup_v1_resolution',serialize($spec));$drain();loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Expired consent held');
    $original=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$spec=YOWCL_Free_Migrations::preview('signup','canonical');$fingerprint=YOWCL_Free_Migrations::resolution_fingerprint('signup',$spec);
    $v=maybe_unserialize(maybe_unserialize(YOWCL_Free_Migrations::read('loyalty_extra_points_rules')));$v['unknown']='fresh sibling';$store('loyalty_extra_points_rules',serialize(serialize($v)),'yes');
    $deny(static function()use($fingerprint){YOWCL_Free_Migrations::resolve('signup','canonical',$fingerprint,wp_create_nonce('loyf_resolve_signup'));},'migration_resolution_stale');
    $fingerprint=YOWCL_Free_Migrations::resolution_fingerprint('signup',YOWCL_Free_Migrations::preview('signup','canonical'));
    $fault=static function($sql)use($wpdb){return 0===strpos($sql,'INSERT INTO '.$wpdb->options)&&strpos($sql,"'loyf_migration_signup_v1',")!==false?'SELECT * FROM loyf27_direct_failure':$sql;};add_filter('query',$fault,PHP_INT_MAX);
    try{$deny(static function()use($fingerprint){YOWCL_Free_Migrations::resolve('signup','canonical',$fingerprint,wp_create_nonce('loyf_resolve_signup'));},'migration_write_failed');}finally{remove_filter('query',$fault,PHP_INT_MAX);}
    loyf_equal($original,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Failed direct confirmation retains exact expired intent');YOWCL_Free_Migrations::schedule();loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Failed direct request never renews worker authority');
    $direct('signup','canonical');loyf_equal($original,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Direct recovery preserves original evidence and expiry');loyf_equal('fresh sibling',maybe_unserialize(maybe_unserialize(YOWCL_Free_Migrations::read('loyalty_extra_points_rules')))['unknown'],'Fresh direct recovery preserves shared sibling');

    // A worker keeps bounded retry authority after uncertain COMMIT and never replays a committed witness.
    foreach(array(false,true) as $durable) {
        $reset();$admit(array('signup'=>'disable'));$attempted=false;$fault=static function($sql)use($wpdb,$durable,&$attempted){if('COMMIT'===$sql&&!$attempted){$attempted=true;if($durable){mysqli_query($wpdb->dbh,'COMMIT');}return 'SELECT * FROM loyf27_worker_commit_response';}return $sql;};
        add_filter('query',$fault,PHP_INT_MAX);try{$drain();}finally{remove_filter('query',$fault,PHP_INT_MAX);}
        loyf_assert($attempted&&YOWCL_Free_Migrations::ready('signup'),'Worker verifies durable completion or bounded retry after uncertain COMMIT');loyf_equal($durable?1:2,get_option('loyf_migration_signup_v1_background')['attempts'],'Committed witness prevents another worker attempt');loyf_equal(0,YOWCL_Free_Core::extra('signup'),'Worker Disable converges without economic mutation');
    }
    // Direct same-intent recovery must distinguish an uncertain COMMIT from a verified rejection.
    foreach(array(false,true) as $durable) {
        $reset();$admit(array('signup'=>'disable'));$spec=get_option('loyf_migration_signup_v1_resolution');$spec['consent']['issued']=time()-86401;$spec['consent']['expires']=time()-1;$store('loyf_migration_signup_v1_resolution',serialize($spec),'yes');
        $original=$wpdb->get_row($wpdb->prepare("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",'loyf_migration_signup_v1_resolution'),ARRAY_A);$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$attempted=false;
        $fault=static function($sql)use($wpdb,$durable,&$attempted){if('COMMIT'===$sql&&!$attempted){$attempted=true;if($durable){mysqli_query($wpdb->dbh,'COMMIT');}return 'SELECT * FROM loyf27_direct_commit_response';}return $sql;};
        add_filter('query',$fault,PHP_INT_MAX);try{$direct('signup','disable','unknown');}finally{remove_filter('query',$fault,PHP_INT_MAX);}
        loyf_assert($attempted,'Actual direct COMMIT boundary exercised');loyf_equal($durable,YOWCL_Free_Migrations::ready('signup'),'Storage determines completion after uncertain response');
        if($durable){loyf_equal(0,YOWCL_Free_Core::extra('signup'),'Durable direct Disable is effective');}else{loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Failed COMMIT rolls back owned target');}
        loyf_equal($original,$wpdb->get_row($wpdb->prepare("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",'loyf_migration_signup_v1_resolution'),ARRAY_A),'Uncertain direct result retains intent bytes/autoload');loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Direct recovery creates no replacement audit');
        $_GET=array('feature'=>'signup','result'=>'unknown');ob_start();YOWCL_Free_Migrations::render_review();$html=ob_get_clean();$_GET=array();loyf_assert(strpos($html,'The decision result could not be verified. It may have committed.')!==false&&strpos($html,'The decision could not be confirmed.')===false,'Unknown direct outcome never claims definitive failure');
        if(!$durable){YOWCL_Free_Migrations::schedule();loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Uncertain direct request never renews expired worker authority');$direct('signup','disable');}else{$direct('signup','disable','already_confirmed');}
        $drain();loyf_equal(0,YOWCL_Free_Core::extra('signup'),'Retry/old worker preserve terminal direct Disable');
    }

    // Cache invalidation after a successful COMMIT is also outside definitive failure authority.
    $reset();$admit(array('signup'=>'disable'));$original=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$cache=$GLOBALS['wp_object_cache'];
    $fault_cache=$cache_fault('loyalty_extra_points_rules');
    $GLOBALS['wp_object_cache']=$fault_cache;$fault=static function($sql)use($fault_cache){if('COMMIT'===$sql){$fault_cache->armed=true;}return $sql;};add_filter('query',$fault,PHP_INT_MAX);
    try{$direct('signup','disable','unknown');}finally{remove_filter('query',$fault,PHP_INT_MAX);$GLOBALS['wp_object_cache']=$cache;wp_cache_flush();}
    loyf_assert(YOWCL_Free_Migrations::ready('signup'),'Post-COMMIT cache failure retains verified witness');loyf_equal($original,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Post-COMMIT cache failure preserves original intent');loyf_equal(0,YOWCL_Free_Core::extra('signup'),'Post-COMMIT cache failure cannot report rollback');

    // A valid pre-transaction snapshot cannot authorize a different stored intent.
    foreach(array('worker','direct') as $operation){foreach(array('corrupt','delete','replace') as $change){foreach(array('before','snapshot') as $timing){
        $reset();$admit(array('signup'=>'disable'));$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$original=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$changed=false;$expected=null;
        $fault=static function($sql)use($wpdb,$original,$change,$timing,&$changed,&$expected){if(!$changed&&('before'===$timing?'START TRANSACTION'===$sql:strpos($sql,"option_name='active_plugins' FOR UPDATE")!==false)){$changed=true;if('snapshot'===$timing){$wpdb->get_var("SELECT option_value FROM {$wpdb->options} WHERE option_name='active_plugins'");}$other=new mysqli(getenv('LOY_DB_HOST'),DB_USER,DB_PASSWORD,DB_NAME,(int)(getenv('LOY_DB_PORT')?:3306));if('delete'===$change){loyf_assert($other->query("DELETE FROM {$wpdb->options} WHERE option_name='loyf_migration_signup_v1_resolution'"),'Independent intent deletion');}else{$expected='corrupt pending intent';if('replace'===$change){$spec=unserialize($original);$spec['consent']['batch']=wp_generate_uuid4();$expected=serialize($spec);}$stmt=$other->prepare("UPDATE {$wpdb->options} SET option_value=? WHERE option_name='loyf_migration_signup_v1_resolution'");$stmt->bind_param('s',$expected);loyf_assert($stmt->execute()&&1===$stmt->affected_rows,'Independent intent replacement');$stmt->close();}$other->close();}return $sql;};add_filter('query',$fault,PHP_INT_MAX);
        try{if('direct'===$operation){$direct('signup','disable','unconfirmed');}else{$drain();}}finally{remove_filter('query',$fault,PHP_INT_MAX);}
        loyf_assert($changed&&!YOWCL_Free_Migrations::ready('signup'),'Changed current intent refuses completion');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Changed intent retains target');loyf_equal($expected,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Changed intent is not overwritten');loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Changed intent creates no audit');
    }}}

    // Permission must use current locking reads even after an InnoDB consistent snapshot.
    $actor=wp_insert_user(array('user_login'=>'loyf27_snapshot_'.substr(wp_generate_uuid4(),0,8),'user_pass'=>'disposable-only','role'=>'administrator'));
    foreach(array('worker','admit','direct','replace') as $operation){foreach(array('caps','roles') as $change){
        wp_set_current_user(1);$reset();(new WP_User($actor))->set_role('administrator');wp_set_current_user($actor);if('admit'!==$operation){$admit(array('signup'=>'disable'));}if('replace'===$operation){$edit('loyalty_extra_points_rules',array('signup_points'=>'99'));}
        $target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$pending=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$role_name=$wpdb->prefix.'user_roles';$roles=$wpdb->get_row($wpdb->prepare("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",$role_name),ARRAY_A);$tx=false;$revoked=false;
        $fault=static function($sql)use($wpdb,$actor,$change,$role_name,$roles,&$tx,&$revoked){if('START TRANSACTION'===$sql){$tx=true;}if($tx&&!$revoked&&strpos($sql,"option_name='".$role_name."' FOR UPDATE")!==false){$revoked=true;$wpdb->get_var("SELECT option_value FROM {$wpdb->options} WHERE option_name='active_plugins'");$other=new mysqli(getenv('LOY_DB_HOST'),DB_USER,DB_PASSWORD,DB_NAME,(int)(getenv('LOY_DB_PORT')?:3306));if('caps'===$change){$raw=serialize(array('subscriber'=>true));$key=$wpdb->prefix.'capabilities';$stmt=$other->prepare("UPDATE {$wpdb->usermeta} SET meta_value=? WHERE user_id=? AND meta_key=?");$stmt->bind_param('sis',$raw,$actor,$key);}else{$map=unserialize($roles['option_value']);$map['administrator']['capabilities']['manage_options']=false;$raw=serialize($map);$stmt=$other->prepare("UPDATE {$wpdb->options} SET option_value=? WHERE option_name=?");$stmt->bind_param('ss',$raw,$role_name);}loyf_assert($stmt->execute()&&1===$stmt->affected_rows,'Independent permission revocation after consistent snapshot');$stmt->close();$other->close();}return $sql;};add_filter('query',$fault,PHP_INT_MAX);
        try{if('worker'===$operation){$drain();}elseif('admit'===$operation){$deny(static function()use($admit){$admit(array('signup'=>'disable'));},'migration_resolution_denied');}elseif('direct'===$operation){$direct('signup','disable','unconfirmed');}else{$replacement('signup','disable','unconfirmed');}}finally{remove_filter('query',$fault,PHP_INT_MAX);$store($role_name,$roles['option_value'],$roles['autoload']);$GLOBALS['wp_roles']=new WP_Roles(get_current_blog_id());clean_user_cache($actor);wp_set_current_user(0);wp_set_current_user(1);}
        loyf_assert($revoked&&!YOWCL_Free_Migrations::ready('signup'),'Current permission refuses completion after snapshot');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Snapshot cannot grant target write');loyf_equal($pending,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Snapshot cannot grant intent write');loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Snapshot cannot grant audit');
    }}
    require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($actor);$actor=0;

    // Once current permissions are read, concurrent revocation cannot cross COMMIT.
    foreach(array('caps','roles') as $change){
        $reset();$admit(array('signup'=>'disable'));$blocked=false;$fault=static function($sql)use($wpdb,$change,&$blocked){if(!$blocked&&0===strpos($sql,'INSERT INTO '.$wpdb->options)&&strpos($sql,"'loyf_migration_signup_v1',")!==false){$blocked=true;$other=new mysqli(getenv('LOY_DB_HOST'),DB_USER,DB_PASSWORD,DB_NAME,(int)(getenv('LOY_DB_PORT')?:3306));$other->query('SET SESSION innodb_lock_wait_timeout=1');$query='caps'===$change?$wpdb->prepare("UPDATE {$wpdb->usermeta} SET meta_value=%s WHERE user_id=1 AND meta_key=%s",serialize(array('subscriber'=>true)),$wpdb->prefix.'capabilities'):$wpdb->prepare("UPDATE {$wpdb->options} SET option_value=%s WHERE option_name=%s",serialize(array()),$wpdb->prefix.'user_roles');try{$ok=$other->query($query);loyf_assert(false===$ok&&1205===$other->errno,'Concurrent permission write is locked until completion');}catch(mysqli_sql_exception $e){loyf_equal(1205,$e->getCode(),'Current permission lock blocks revocation');}finally{$other->close();}}return $sql;};add_filter('query',$fault,PHP_INT_MAX);
        try{$drain();}finally{remove_filter('query',$fault,PHP_INT_MAX);}
        loyf_assert($blocked&&YOWCL_Free_Migrations::ready('signup'),'Current authorized permission remains serialized through completion');
    }

    // Initial request permission cannot survive independent revocation before serialization.
    $reset();$actor=wp_insert_user(array('user_login'=>'loyf27_tx_'.substr(wp_generate_uuid4(),0,8),'user_pass'=>'disposable-only','role'=>'administrator'));
    foreach(array('admit','direct','replace','retry') as $operation) {
        wp_set_current_user(1);$reset();(new WP_User($actor))->set_role('administrator');
        if('admit'!==$operation){$admit(array('signup'=>'disable'));}
        if('replace'===$operation){$edit('loyalty_extra_points_rules',array('signup_points'=>'99'));}
        if('retry'===$operation){$work=get_option('loyf_migration_signup_v1_background');$work['attempts']=3;$work['error']='migration_write_failed';$store('loyf_migration_signup_v1_background',serialize($work));}
        $target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$pending=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$work=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_background');$queued=as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids');
        wp_set_current_user(0);wp_set_current_user($actor);loyf_assert(current_user_can('manage_options'),'Interactive request starts authorized');$revoked=false;
        $fault=static function($sql)use($wpdb,$actor,$operation,&$revoked){if(!$revoked&&('retry'===$operation?strpos($sql,'GET_LOCK(')!==false:'START TRANSACTION'===$sql)){
            $other=new mysqli(getenv('LOY_DB_HOST'),DB_USER,DB_PASSWORD,DB_NAME,(int)(getenv('LOY_DB_PORT')?:3306));$caps=serialize(array('subscriber'=>true));$key=$wpdb->prefix.'capabilities';$stmt=$other->prepare("UPDATE {$wpdb->usermeta} SET meta_value=? WHERE user_id=? AND meta_key=?");$stmt->bind_param('sis',$caps,$actor,$key);loyf_assert($stmt->execute()&&1===$stmt->affected_rows,'Independent native actor revocation committed');$stmt->close();$other->close();$revoked=true;
        }return $sql;};
        add_filter('query',$fault,PHP_INT_MAX);
        try{
            if('admit'===$operation){$vector=$choices(array('signup'=>'disable'));$_SERVER['REQUEST_METHOD']='POST';$_POST=array('choices'=>$vector,'batch'=>wp_generate_uuid4(),'_wpnonce'=>wp_create_nonce('loyf_confirm_migrations'));$redirect=static function($url){throw new RuntimeException('redirect:'.$url);};add_filter('wp_redirect',$redirect,0);try{do_action('admin_post_loyf_confirm_migrations');throw new LogicException('Missing admission POST');}catch(RuntimeException $e){loyf_assert(strpos($e->getMessage(),'batch_result=unconfirmed')!==false,'Revoked interactive admission refused');}finally{remove_filter('wp_redirect',$redirect,0);$_POST=array();}}
            elseif('direct'===$operation){$direct('signup','disable','unconfirmed');}
            elseif('replace'===$operation){$replacement('signup','disable','unconfirmed');}
            else{$_SERVER['REQUEST_METHOD']='POST';$_POST=array('feature'=>'signup','_wpnonce'=>wp_create_nonce('loyf_retry_signup'));$redirect=static function($url){throw new RuntimeException('redirect:'.$url);};add_filter('wp_redirect',$redirect,0);try{do_action('admin_post_loyf_retry_migration');throw new LogicException('Missing retry POST');}catch(RuntimeException $e){loyf_assert(strpos($e->getMessage(),'#loyf-status')!==false,'Denied retry returns to status');}finally{remove_filter('wp_redirect',$redirect,0);$_POST=array();}}
        }finally{remove_filter('query',$fault,PHP_INT_MAX);wp_set_current_user(1);clean_user_cache($actor);}
        loyf_assert($revoked&&!user_can(new WP_User($actor),'manage_options'),'Fresh actor permission reflects independent revocation');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Revoked actor cannot change owned target');loyf_equal($pending,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Revoked actor cannot admit/rewrite intent');loyf_equal($work,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_background'),'Revoked actor cannot reset worker authority');loyf_assert(!YOWCL_Free_Migrations::ready('signup')&&null===YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Revoked actor creates no witness/audit');loyf_equal($queued,as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids'),'Revocation creates no extra delivery');
    }
    // A fresh WP_User alone is insufficient when WP_Roles was cached before revocation.
    foreach(array('admit','direct') as $operation) {
        wp_set_current_user(1);$reset();if('direct'===$operation){$admit(array('signup'=>'disable'));}$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$pending=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$role_name=$wpdb->prefix.'user_roles';$roles=$wpdb->get_row($wpdb->prepare("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",$role_name),ARRAY_A);wp_set_current_user(0);wp_set_current_user(1);loyf_assert(current_user_can('manage_options'),'Site-role request starts authorized');$revoked=false;
        $fault=static function($sql)use($wpdb,$role_name,$roles,&$revoked){if(!$revoked&&'START TRANSACTION'===$sql){$other=new mysqli(getenv('LOY_DB_HOST'),DB_USER,DB_PASSWORD,DB_NAME,(int)(getenv('LOY_DB_PORT')?:3306));$map=unserialize($roles['option_value']);$map['administrator']['capabilities']['manage_options']=false;$raw=serialize($map);$stmt=$other->prepare("UPDATE {$wpdb->options} SET option_value=? WHERE option_name=?");$stmt->bind_param('ss',$raw,$role_name);loyf_assert($stmt->execute(),'Independent native site-role revocation');$stmt->close();$other->close();$revoked=true;}return $sql;};add_filter('query',$fault,PHP_INT_MAX);
        try{if('direct'===$operation){$direct('signup','disable','unconfirmed');}else{$deny(static function()use($admit){$admit(array('signup'=>'disable'));},'migration_resolution_denied');}}finally{remove_filter('query',$fault,PHP_INT_MAX);$store($role_name,$roles['option_value'],$roles['autoload']);$GLOBALS['wp_roles']=new WP_Roles(get_current_blog_id());wp_set_current_user(0);wp_set_current_user(1);}
        loyf_assert($revoked,'Actual cached role-definition boundary exercised');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Role revocation blocks owned target mutation');loyf_equal($pending,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Role revocation blocks new intent');loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Role revocation creates no witness');
    }
    require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($actor);$actor=0;

    $reset();$actor=wp_insert_user(array('user_login'=>'loyf27_'.substr(wp_generate_uuid4(),0,8),'user_pass'=>'disposable-only','role'=>'administrator'));wp_set_current_user($actor);$admit(array('signup'=>'canonical'));(new WP_User($actor))->set_role('subscriber');wp_set_current_user(1);$drain();loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Revoked actor held');$original=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$direct('signup','canonical');loyf_equal($original,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'New current actor direct recovery retains revoked actor evidence');
    $reset();$spec=YOWCL_Free_Migrations::preview('signup','canonical');$store('loyf_migration_signup_v1_resolution',serialize($spec));YOWCL_Free_Migrations::schedule();loyf_equal(array(),as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids'),'Old pending never auto replayed');
    // Finite real witness failure retries and no budget restart on later boots.
    $reset();$admit(array('signup'=>'canonical'));$fault=static function($sql)use($wpdb){return strpos($sql,'INSERT INTO '.$wpdb->options)!==false&&strpos($sql,"'loyf_migration_signup_v1'")!==false?'SELECT * FROM loyf27_no_witness_table':$sql;};add_filter('query',$fault,PHP_INT_MAX);try{$drain();}finally{remove_filter('query',$fault,PHP_INT_MAX);}
    loyf_equal(3,get_option('loyf_migration_signup_v1_background')['attempts'],'Three attempts maximum');YOWCL_Free_Migrations::schedule();loyf_equal('failed',YOWCL_Free_Migrations::status()['state'],'Honest exhausted state');loyf_equal(array(),as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids'),'No infinite retry');
    // Pending cron held too long is stalled, not a permanent running label.
    $reset();$admit(array('signup'=>'canonical'));$work=get_option('loyf_migration_signup_v1_background');$work['updated']=time()-901;$store('loyf_migration_signup_v1_background',serialize($work));loyf_equal('migration_stalled',YOWCL_Free_Migrations::status()['features']['signup']['reason'],'No-WP-Cron honest status');
    // Legacy-source drift, nonce/capability denial, and native edition owner recheck.
    $reset();$admit(array('review'=>'legacy'));$v=maybe_unserialize(maybe_unserialize(YOWCL_Free_Migrations::read('loyalty_extra_points_rules')));$v['review_points']='26';$store('loyalty_extra_points_rules',serialize(serialize($v)),'yes');$drain();loyf_assert(!YOWCL_Free_Migrations::ready('review'),'Later source edit held');$fingerprint=YOWCL_Free_Migrations::resolution_fingerprint('review',YOWCL_Free_Migrations::preview('review','legacy'));$deny(static function()use($fingerprint){YOWCL_Free_Migrations::resolve('review','legacy',$fingerprint,wp_create_nonce('loyf_resolve_review'));},'migration_source_changed');
    $reset();$vector=$choices(array('signup'=>'canonical'));$deny(static function()use($vector){YOWCL_Free_Migrations::admit($vector,wp_generate_uuid4(),'invalid');},'migration_resolution_denied');wp_set_current_user($actor);$deny(static function()use($vector){YOWCL_Free_Migrations::admit($vector,wp_generate_uuid4(),wp_create_nonce('loyf_confirm_migrations'));},'migration_resolution_denied');wp_set_current_user(1);
    $reset();$admit(array('signup'=>'canonical'));$active=$wpdb->get_row($wpdb->prepare("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name=%s",'active_plugins'),ARRAY_A);$plugins=maybe_unserialize($active['option_value']);$plugins[]='wc-loyalty/wc-loyalty.php';$store('active_plugins',serialize($plugins),$active['autoload']);try{$drain();loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Stale Free action denied under Premium owner');}finally{$store('active_plugins',$active['option_value'],$active['autoload']);}$original=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$direct('signup','canonical');loyf_equal($original,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Returned Free owner direct confirmation preserves old approval');
    // Missing/uninitialized AS stays inspectable and never admits a worker mutation.
    $reset();$admit(array('signup'=>'canonical'));$property=new ReflectionProperty('ActionScheduler','data_store_initialized');$property->setAccessible(true);$initialized=$property->getValue();$property->setValue(null,false);try{YOWCL_Free_Migrations::worker('signup',get_option('loyf_migration_signup_v1_background')['run']);loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Unavailable AS cannot execute');loyf_equal('migration_scheduler_unavailable',YOWCL_Free_Migrations::status()['features']['signup']['reason'],'Missing AS honest status');}finally{$property->setValue(null,$initialized);}
    // Fail the actual post-INSERT witness readback; target and witness must roll back together.
    $reset();$admit(array('signup'=>'disable'));$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$readback=false;$injected=false;
    $fault=static function($sql)use(&$readback,&$injected){if(0===strpos($sql,'INSERT INTO ')&&strpos($sql,"'loyf_migration_signup_v1',")!==false){$readback=true;}elseif($readback&&0===strpos($sql,'SELECT option_value')&&strpos($sql,"'loyf_migration_signup_v1'")!==false){$readback=false;$injected=true;return 'SELECT * FROM loyf27_no_readback_table';}return $sql;};add_filter('query',$fault,PHP_INT_MAX);try{$id=as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>1),'ids')[0];ActionScheduler_QueueRunner::instance()->process_action($id,'LOYF-27 readback');}finally{remove_filter('query',$fault,PHP_INT_MAX);}loyf_assert($injected&&!YOWCL_Free_Migrations::ready('signup'),'No success without readback');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Readback rollback exact');$drain();loyf_assert(YOWCL_Free_Migrations::ready('signup'),'Same live consent transient recovery');
    // A real lost connection at the target/witness boundary cannot replay an autocommit witness.
    $reset();$admit(array('signup'=>'disable'));$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$killed=false;
    $fault=static function($sql)use($wpdb,&$killed){if(!$killed&&0===strpos($sql,'INSERT INTO ')&&strpos($sql,"'loyf_migration_signup_v1',")!==false){$db=new mysqli(getenv('LOY_DB_HOST'),DB_USER,DB_PASSWORD,DB_NAME,(int)getenv('LOY_DB_PORT'));$db->query('KILL '.(int)mysqli_thread_id($wpdb->dbh));$db->close();$killed=true;}return $sql;};add_filter('query',$fault,PHP_INT_MAX);try{$drain();}finally{remove_filter('query',$fault,PHP_INT_MAX);}$wpdb->check_connection(false);wp_cache_flush();loyf_assert($killed&&!YOWCL_Free_Migrations::ready('signup'),'Lost original owner cannot manufacture witness');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Lost connection rolls back target');
    // Actual process exit during a worker leaves no completion; retained attempts expose the stalled run.
    $reset();$admit(array('signup'=>'disable'));$id=as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>1),'ids')[0];$log=tempnam(sys_get_temp_dir(),'loyf27-abort-');$cmd=array(PHP_BINARY,getenv('LOYF_WP_CLI_PHAR'),'--path='.ABSPATH,'eval-file',__FILE__,'worker',(string)$id,'abort','--quiet');$process=proc_open($cmd,array(0=>array('file','/dev/null','r'),1=>array('file',$log,'a'),2=>array('file',$log,'a')),$pipes);loyf_equal(9,proc_close($process),'Actual aborted worker');unlink($log);loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Aborted worker no witness');$work=get_option('loyf_migration_signup_v1_background');loyf_equal(1,$work['attempts'],'Attempt retained before abort');$work['updated']=time()-901;$store('loyf_migration_signup_v1_background',serialize($work));loyf_equal('migration_stalled',YOWCL_Free_Migrations::status()['features']['signup']['reason'],'Aborted run eventually stalls');ActionScheduler::store()->cancel_action($id);
    // Two independent real AS deliveries share the original options owner.
    $reset();$admit(array('signup'=>'canonical'));$work=get_option('loyf_migration_signup_v1_background');as_schedule_single_action(time(),YOWCL_Free_Migrations::HOOK,array('signup',$work['run']),YOWCL_Free_Migrations::GROUP,false);
    $ids=as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>20),'ids');loyf_equal(2,count($ids),'Duplicate native actions');
    foreach($ids as$id){$log=tempnam(sys_get_temp_dir(),'loyf27-worker-');$cmd=array(PHP_BINARY,getenv('LOYF_WP_CLI_PHAR'),'--path='.ABSPATH,'eval-file',__FILE__,'worker',(string)$id,'--quiet');$process=proc_open($cmd,array(0=>array('file','/dev/null','r'),1=>array('file',$log,'a'),2=>array('file',$log,'a')),$pipes);loyf_assert(is_resource($process),'Independent worker');$children[]=array($process,$log);}
    foreach($children as$i=>$child){loyf_equal(0,proc_close($child[0]),'Independent native worker '.file_get_contents($child[1]));$children[$i][0]=null;unlink($child[1]);}
    loyf_assert(YOWCL_Free_Migrations::ready('signup'),'Two workers converge once');loyf_equal($before,$business(),'All native cases preserve balances/history/roles');
    // Round2: only attributable actual drift admits a fresh synchronous replacement.
    $reset();$admit(array('signup'=>'canonical'));$deny(static function(){YOWCL_Free_Migrations::replacement_preview('signup','disable');},'migration_replacement_unavailable');
    $edit('loyalty_extra_points_rules',array('unknown'=>'sibling only','login_points'=>'19'));$deny(static function(){YOWCL_Free_Migrations::replacement_preview('signup','disable');},'migration_replacement_unavailable');
    $edit('loyalty_extra_points_rules',array('signup_points'=>'99','signup_enabled'=>'yes'));$original=$wpdb->get_row("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name='loyf_migration_signup_v1_resolution'",ARRAY_A);$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');
    $proposal=YOWCL_Free_Migrations::replacement_preview('signup','disable');$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],'invalid');},'migration_resolution_denied');
    $edit('loyalty_extra_points_rules',array('signup_points'=>'100'));$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],wp_create_nonce('loyf_replace_signup'));},'migration_resolution_stale');
    $replacement('signup','canonical');loyf_equal(100,YOWCL_Free_Core::extra('signup'),'Replacement uses live current reward');$audit=get_option('loyf_migration_signup_v1_supersession');loyf_equal(hash('sha256',$original['option_value']),$audit['original_digest'],'Audit references immutable original');loyf_equal($original,$wpdb->get_row("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name='loyf_migration_signup_v1_resolution'",ARRAY_A),'Original row/autoload exact after replacement');loyf_equal('no',$wpdb->get_var("SELECT autoload FROM {$wpdb->options} WHERE option_name='loyf_migration_signup_v1_supersession'"),'One non-autoloaded audit');loyf_assert(strpos(serialize($audit),'sibling only')===false,'Audit excludes unknown container values');
    $audit_raw=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession');loyf_equal('already_confirmed',YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],wp_create_nonce('loyf_replace_signup')),'Second admin cannot change completed choice');$drain();loyf_equal($audit_raw,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Old AS and repeat POST leave one terminal audit');
    // Stale original evidence, historical evidence and frozen captures are never replaced.
    $reset();$admit(array('signup'=>'canonical'));$edit('loyalty_extra_points_rules',array('signup_points'=>'66'));$proposal=YOWCL_Free_Migrations::replacement_preview('signup','disable');$old=get_option('loyf_migration_signup_v1_resolution');$old['consent']['batch']=wp_generate_uuid4();$store('loyf_migration_signup_v1_resolution',serialize($old));$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],wp_create_nonce('loyf_replace_signup'));},'migration_resolution_stale');
    $store('loyf_migration_signup_v1_before',serialize(array('frozen'=>'evidence')));$deny(static function(){YOWCL_Free_Migrations::replacement_preview('signup','disable');},'migration_replacement_unavailable');delete_option('loyf_migration_signup_v1_before');
    unset($old['consent']);$store('loyf_migration_signup_v1_resolution',serialize($old));$deny(static function(){YOWCL_Free_Migrations::replacement_preview('signup','disable');},'migration_resolution_pending');
    // Source drift can authorize a different freshly reviewed mode, never replay the old patch.
    $reset();$admit(array('review'=>'legacy'));$edit('loyalty_extra_points_rules',array('review_points'=>'77'));$proposal=YOWCL_Free_Migrations::replacement_preview('review','legacy');$edit('loyalty_extra_points_rules',array('review_points'=>'78'));$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('review','legacy',$proposal['fingerprint'],wp_create_nonce('loyf_replace_review'));},'migration_resolution_stale');$replacement('review','legacy');loyf_equal(78,YOWCL_Free_Core::extra('review'),'Live selected legacy source');
    $reset();$admit(array('levelup'=>'legacy'));$store('loyalty_extra_levelup_points_rules',serialize(array('customer'=>array('awarded'=>'80','private'=>'not audited'))));$replacement('levelup','legacy');loyf_equal('80',YOWCL_Free_Core::level_rules()['customer']['awarded'],'Live role-map replacement');loyf_assert(strpos(serialize(get_option('loyf_migration_levelup_v1_supersession')),'not audited')===false,'Audit excludes dormant role fields');
    $reset();$admit(array('email_reward'=>'legacy'));$store('loyalty_notification_email',serialize(array('level_update'=>true)));$deny(static function(){YOWCL_Free_Migrations::replacement_preview('email_reward','legacy');},'migration_legacy_source_missing');$replacement('email_reward','disable');loyf_equal('no',get_option('woocommerce_yowcl_loyalty_points_reward_settings')['enabled'],'Absent legacy cannot mean OFF; deliberate supported disable remains possible');
    // Redemption context change is independently reviewed; exact fractions/siblings survive.
    $reset();$admit(array('redemption'=>'canonical'));$currency=YOWCL_Free_Migrations::read('woocommerce_currency');$store('woocommerce_currency','EUR');$store('loyalty_points_using_point','no');$proposal=YOWCL_Free_Migrations::replacement_preview('redemption','canonical');$store('loyalty_points_using_point','yes');$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('redemption','canonical',$proposal['fingerprint'],wp_create_nonce('loyf_replace_redemption'));},'migration_resolution_stale');$target=YOWCL_Free_Migrations::read('loyalty_points_using_rules');$replacement('redemption','canonical');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_points_using_rules'),'Replacement preserves exact0.7010 raw wrapper');$store('woocommerce_currency',$currency);
    // Each target/witness/audit SQL fault rolls back the same complete feature transaction.
    foreach(array('target','witness','audit') as$boundary){$reset();$admit(array('signup'=>'canonical'));$edit('loyalty_extra_points_rules',array('signup_points'=>'55'));$original=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$proposal=YOWCL_Free_Migrations::replacement_preview('signup','disable');$fault=static function($sql)use($boundary){$name='target'===$boundary?'loyalty_extra_points_rules':('witness'===$boundary?'loyf_migration_signup_v1':'loyf_migration_signup_v1_supersession');return (0===strpos($sql,'INSERT INTO ')||0===strpos($sql,'UPDATE ')) && strpos($sql,"'".$name."'")!==false?'SELECT * FROM loyf27_supersession_fault':$sql;};add_filter('query',$fault,PHP_INT_MAX);try{$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],wp_create_nonce('loyf_replace_signup'));},'migration_write_failed');}finally{remove_filter('query',$fault,PHP_INT_MAX);}loyf_equal($original,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution'),'Fault preserves original');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Fault rolls back target');loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Fault has no audit');loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Fault has no success witness');$replacement('signup','disable');}
    // Legacy replacement validates all retained exchange terms, not only added default bounds.
    foreach(array(array('points',null),array('amount',null),array('points','not-numeric'),array('amount','not-numeric'),array('points',-1),array('amount','1e999'),array('min_points',array('opaque'=>'bad')),array('max_points',-1),array('min_cart','not-numeric')) as $case) {
        $reset();$admit(array('redemption'=>'canonical'));$original=YOWCL_Free_Migrations::read('loyf_migration_redemption_v1_resolution');$rules=maybe_unserialize(maybe_unserialize(YOWCL_Free_Migrations::read('loyalty_points_using_rules')));if(null===$case[1]){unset($rules[$case[0]]);}else{$rules[$case[0]]=$case[1];}$store('loyalty_points_using_rules',serialize(serialize($rules)),'yes');$invalid=YOWCL_Free_Migrations::read('loyalty_points_using_rules');
        $deny(static function(){YOWCL_Free_Migrations::replacement_preview('redemption','legacy');},null===$case[1]?'migration_legacy_source_missing':'migration_malformed_points');loyf_equal($invalid,YOWCL_Free_Migrations::read('loyalty_points_using_rules'),'Invalid live exchange terms remain exact on denial');loyf_assert(!YOWCL_Free_Migrations::ready('redemption')&&null===YOWCL_Free_Migrations::read('loyf_migration_redemption_v1_supersession'),'Invalid legacy source creates no witness/audit');
        $replacement('redemption','disable');loyf_equal($original,YOWCL_Free_Migrations::read('loyf_migration_redemption_v1_resolution'),'Deliberate narrow Disable preserves original reviewed evidence');$drain();loyf_equal('003',maybe_unserialize(maybe_unserialize(YOWCL_Free_Migrations::read('loyalty_points_using_rules')))['unknown'],'Disable preserves unrelated redemption bytes');
    }
    $reset();$admit(array('redemption'=>'canonical'));$store('loyalty_points_using_point','no');$edit('loyalty_points_using_rules',array('points'=>'','amount'=>''));$blank=YOWCL_Free_Migrations::read('loyalty_points_using_rules');$replacement('redemption','legacy');loyf_equal($blank,YOWCL_Free_Migrations::read('loyalty_points_using_rules'),'Known disabled/blank exchange semantics remain byte-exact');

    $reset();$admit(array('signup'=>'canonical'));$edit('loyalty_extra_points_rules',array('signup_points'=>'55'));$committed=false;$fault=static function($sql)use($wpdb,&$committed){if('COMMIT'===$sql&&!$committed){mysqli_query($wpdb->dbh,'COMMIT');$committed=true;return 'SELECT * FROM loyf27_replacement_commit_response';}return $sql;};add_filter('query',$fault,PHP_INT_MAX);try{$replacement('signup','disable','unknown');}finally{remove_filter('query',$fault,PHP_INT_MAX);}loyf_assert(YOWCL_Free_Migrations::ready('signup')&&get_option('loyf_migration_signup_v1_supersession')!==false,'Unknown response has atomically committed audit/witness');$drain();loyf_equal(0,YOWCL_Free_Core::extra('signup'),'Old worker cannot undo new disable');
    // Failure of audit readback or original connection cannot leave target/witness/audit behind.
    foreach(array('readback','disconnect') as$boundary){$reset();$admit(array('signup'=>'canonical'));$edit('loyalty_extra_points_rules',array('signup_points'=>'55'));$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$proposal=YOWCL_Free_Migrations::replacement_preview('signup','disable');$inserted=false;$injected=false;
      $fault=static function($sql)use($wpdb,$boundary,&$inserted,&$injected){if(!$injected&&0===strpos($sql,'INSERT INTO ')&&strpos($sql,"'loyf_migration_signup_v1_supersession',")!==false){$inserted=true;if('disconnect'===$boundary){$db=new mysqli(getenv('LOY_DB_HOST'),DB_USER,DB_PASSWORD,DB_NAME,(int)getenv('LOY_DB_PORT'));$db->query('KILL '.(int)mysqli_thread_id($wpdb->dbh));$db->close();$injected=true;}}elseif(!$injected&&$inserted&&0===strpos($sql,'SELECT option_value')&&strpos($sql,"'loyf_migration_signup_v1_supersession'")!==false){$injected=true;return 'SELECT * FROM loyf27_audit_readback_fault';}return $sql;};add_filter('query',$fault,PHP_INT_MAX);try{$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],wp_create_nonce('loyf_replace_signup'));},'disconnect'===$boundary?'migration_ownership_lost':'migration_storage_unavailable');}finally{remove_filter('query',$fault,PHP_INT_MAX);}$wpdb->check_connection(false);wp_cache_flush();loyf_assert($injected,'Actual audit boundary fault');loyf_equal($target,YOWCL_Free_Migrations::read('loyalty_extra_points_rules'),'Failed audit boundary rolls back target');loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Failed audit boundary no witness');loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Failed audit boundary no evidence of completion');}
    // A worker success before the stale direct POST wins; the new request cannot supersede it.
    $reset();$admit(array('signup'=>'canonical'));$unchanged=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$edit('loyalty_extra_points_rules',array('signup_points'=>'55'));$proposal=YOWCL_Free_Migrations::replacement_preview('signup','disable');$store('loyalty_extra_points_rules',$unchanged,'yes');$drain();loyf_assert(YOWCL_Free_Migrations::ready('signup'),'Earlier old worker convergence');loyf_equal('already_confirmed',YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],wp_create_nonce('loyf_replace_signup')),'Prior worker witness defeats stale new choice');loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Old worker success is not supersession');
    // A stale worker that runs first remains held; then a deliberate replacement can finish once.
    $reset();$admit(array('signup'=>'canonical'));$edit('loyalty_extra_points_rules',array('signup_points'=>'55'));$drain();loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'First stale worker refuses owned edit');$replacement('signup','disable');$drain();loyf_equal(0,YOWCL_Free_Core::extra('signup'),'Later fresh direct completion wins safely');
    // Negative authority/data matrix: no repair, no cross-edition or historical admission.
    $reset();$admit(array('signup'=>'canonical'));$edit('loyalty_extra_points_rules',array('signup_points'=>'55'));$proposal=YOWCL_Free_Migrations::replacement_preview('signup','disable');wp_set_current_user($actor);$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],wp_create_nonce('loyf_replace_signup'));},'migration_resolution_denied');wp_set_current_user(1);
    $pending=YOWCL_Free_Migrations::read('loyf_migration_signup_v1_resolution');$target=YOWCL_Free_Migrations::read('loyalty_extra_points_rules');$store('loyalty_extra_points_rules','opaque scalar','yes');$deny(static function(){YOWCL_Free_Migrations::replacement_preview('signup','disable');},'migration_opaque_target');$store('loyalty_extra_points_rules',$target,'yes');
    $store('loyf_migration_signup_v1','malformed');$deny(static function(){YOWCL_Free_Migrations::replacement_preview('signup','disable');},'migration_replacement_unavailable');delete_option('loyf_migration_signup_v1');
    $store('loyf_migration_signup_v1_resolution','malformed');$deny(static function(){YOWCL_Free_Migrations::replacement_preview('signup','disable');},'migration_malformed_option');$store('loyf_migration_signup_v1_resolution',$pending);
    $active=$wpdb->get_row("SELECT option_value,autoload FROM {$wpdb->options} WHERE option_name='active_plugins'",ARRAY_A);$plugins=maybe_unserialize($active['option_value']);$plugins[]='wc-loyalty/wc-loyalty.php';$store('active_plugins',serialize($plugins),$active['autoload']);try{$deny(static function()use($proposal){YOWCL_Free_Migrations::replace_pending('signup','disable',$proposal['fingerprint'],wp_create_nonce('loyf_replace_signup'));},'migration_resolution_denied');}finally{$store('active_plugins',$active['option_value'],$active['autoload']);}
    loyf_equal(null,YOWCL_Free_Migrations::read('loyf_migration_signup_v1_supersession'),'Negative matrix creates no audit');loyf_assert(!YOWCL_Free_Migrations::ready('signup'),'Negative matrix creates no witness');
    // A truly running old AS delivery and the direct POST contend on the same named owner, in both orders.
    foreach(array('worker','replace') as$first){$reset();$admit(array('signup'=>'canonical'));$edit('loyalty_extra_points_rules',array('signup_points'=>'55'));$proposal=YOWCL_Free_Migrations::replacement_preview('signup','disable');$id=as_get_scheduled_actions(array('hook'=>YOWCL_Free_Migrations::HOOK,'status'=>'pending','per_page'=>1),'ids')[0];$gate=tempnam(sys_get_temp_dir(),'loyf27-lock-');unlink($gate);$log=tempnam(sys_get_temp_dir(),'loyf27-race-');$wp=array(PHP_BINARY,getenv('LOYF_WP_CLI_PHAR'),'--path='.ABSPATH,'eval-file',__FILE__);
      $args='worker'===$first?array('worker',(string)$id,'gate',$gate,'--quiet'):array('replace','signup','disable',$proposal['fingerprint'],$gate,'--quiet');$process=proc_open(array_merge($wp,$args),array(0=>array('file','/dev/null','r'),1=>array('file',$log,'a'),2=>array('file',$log,'a')),$pipes);$deadline=microtime(true)+10;while(!is_file($gate)&&microtime(true)<$deadline){usleep(10000);}loyf_assert(is_file($gate),'First native process owns options lock');
      if('worker'===$first){$replacement('signup','disable');}else{ActionScheduler_QueueRunner::instance()->process_action($id,'LOYF27 overlapping old action');}
      loyf_equal(0,proc_close($process),'Contending process completed '.file_get_contents($log));unlink($gate);unlink($log);loyf_assert(YOWCL_Free_Migrations::ready('signup'),'Both real lock orders converge');loyf_equal(0,YOWCL_Free_Core::extra('signup'),'Running old worker cannot override replacement');}
    // Two actual administrator processes are serialized; only one replacement is committed.
    $reset();$admit(array('signup'=>'canonical'));$edit('loyalty_extra_points_rules',array('signup_points'=>'55'));$proposal=YOWCL_Free_Migrations::replacement_preview('signup','disable');$children=array();
    foreach(array(1,2) as$i){$log=tempnam(sys_get_temp_dir(),'loyf27-replace-');$cmd=array(PHP_BINARY,getenv('LOYF_WP_CLI_PHAR'),'--path='.ABSPATH,'eval-file',__FILE__,'replace','signup','disable',$proposal['fingerprint'],'--quiet');$process=proc_open($cmd,array(0=>array('file','/dev/null','r'),1=>array('file',$log,'a'),2=>array('file',$log,'a')),$pipes);$children[]=array($process,$log);}
    $results=array();foreach($children as$i=>$child){loyf_equal(0,proc_close($child[0]),'Native concurrent administrator');$children[$i][0]=null;$results[]=file_get_contents($child[1]);unlink($child[1]);}sort($results);loyf_equal(array('already_confirmed','confirmed'),$results,'One direct completion and terminal replay');loyf_equal($before,$business(),'All replacements preserve balances/history/roles');
    echo "LOYF-27 native background PASS: aggregate POST, atomic admission rollback, duplicate submit/two AS workers, stale terms, partial independent convergence, exact fractions, context drift/lost COMMIT response, immutable direct recovery after expiry/revocation/owner return, old-intent refusal, finite retries/stalled cron, one-time drift replacement with atomic audit/races/unknown response/fault denial; no economic mutations.\n";
} finally {
    foreach($children as$child){if(is_resource($child[0])){proc_terminate($child[0]);proc_close($child[0]);}if(is_file($child[1])){unlink($child[1]);}}
    as_unschedule_all_actions(YOWCL_Free_Migrations::HOOK,null,YOWCL_Free_Migrations::GROUP);
    foreach($saved as$n=>$row){if(null===$row){delete_option($n);}else{$store($n,$row['option_value'],$row['autoload']);}}
    if($notice_exists){update_user_meta(1,'loyf_migration_notice_dismissed',$notice_before);}else{delete_user_meta(1,'loyf_migration_notice_dismissed');}
    if($actor){require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($actor);}wp_set_current_user(1);
}
