<?php
require __DIR__.'/assertions.php';
$actor=get_current_user_id();$saved=get_option(YOWCL_Free_Referral::OPTION,null);wp_set_current_user(1);YOWCL_Free_Referral::save(true,23);
$extras=get_option('loyalty_extra_points_rules');update_option('loyalty_extra_points_rules',array('signup_enabled'=>'no','login_enabled'=>'no'));
function rf_api($method,$body=array()){$r=new WP_REST_Request($method,'/wc/store/v1/checkout');$r->set_header('Nonce',wp_create_nonce('wc_store_api'));$r->set_body_params($body);$v=rest_do_request($r);loyf_assert($v->get_status()<300,'Referral Store '.$method.' '.wp_json_encode($v->get_data()));return json_decode(wp_json_encode($v->get_data()),true);}
try{
 $product=new WC_Product_Simple();$product->set_name('Referral native checkout');$product->set_regular_price(15);$product->set_virtual(true);$product->save();
 $ref=wp_insert_user(array('user_login'=>'referral_origins_r','user_email'=>'rf-origins-r@example.invalid','user_pass'=>'disposable-only','role'=>'customer'));$token=YOWCL_Helper_Referrals::ensure_user_token((int)$ref);
 $address=array('first_name'=>'Referral','last_name'=>'Buyer','address_1'=>'1 Test','city'=>'New York','state'=>'NY','postcode'=>'10001','country'=>'US','email'=>'rf-origins@example.invalid','phone'=>'5550001000');$body=array('billing_address'=>$address,'shipping_address'=>$address,'payment_method'=>'cod');
 $pay=function($context,&$result){if('cod'===$context->payment_method){$result->set_status('success');$result->set_redirect_url($context->order->get_checkout_order_received_url());}};add_action('woocommerce_rest_checkout_process_payment_with_context',$pay,1,2);
 foreach(array('classic','store')as$adapter){$u=wp_insert_user(array('user_login'=>'rf_origins_'.$adapter,'user_email'=>'rf-origins-'.$adapter.'@example.invalid','user_pass'=>'disposable-only','role'=>'customer'));loyf_assert(!is_wp_error($u),'Origin registered user');wp_set_current_user((int)$u);if(!WC()->session){WC()->initialize_session();}if(!WC()->cart){WC()->initialize_cart();}WC()->cart->empty_cart();WC()->cart->add_to_cart($product->get_id());WC()->cart->calculate_totals();WC()->session->set('store_api_draft_order',null);$_COOKIE['yowcl_ref']=$token;
  if('classic'===$adapter){$id=WC()->checkout()->create_order(array('billing_email'=>$address['email'],'payment_method'=>'cod'));loyf_assert(!is_wp_error($id),'Native Classic final');}
  else{$get=rf_api('GET');if($get['order_id']){loyf_equal('',wc_get_order($get['order_id'])->get_meta(YOWCL_Referral_Rewards::TERMS),'GET no referral freeze');}$put=rf_api('PUT',$body);if($put['order_id']){loyf_equal('',wc_get_order($put['order_id'])->get_meta(YOWCL_Referral_Rewards::TERMS),'PUT no referral freeze');}$post=rf_api('POST',$body);$id=$post['order_id'];}
  $o=wc_get_order($id);$o->read_meta_data(true);$t=$o->get_meta(YOWCL_Referral_Rewards::TERMS);loyf_assert(is_array($t)&&count($t['events'])===1,'Final immutable referral receipt');loyf_equal((int)$u,$t['referee'],'Final owner');$o->update_status('processing');$o->update_status('completed');do_action('woocommerce_payment_complete',$id);$row=YOWCL_Points_Transaction::find('referral:link:'.$id.':referrer');loyf_equal(23,(int)$row['available_delta'],'Native origin award once');$o->update_status('cancelled');loyf_assert(YOWCL_Points_Transaction::find('referral:link:'.$id.':referrer:reversal'),'Native origin reversal');
 }
 remove_action('woocommerce_rest_checkout_process_payment_with_context',$pay,1);loyf_balance((int)$ref,0,0,'Native origins reversed once');echo'Native Referral Lite Classic/GET/PUT/POST origins PASS '.getenv('LOYF_STORAGE')."\n";
}finally{wp_set_current_user($actor);update_option('loyalty_extra_points_rules',$extras);if(null===$saved){delete_option(YOWCL_Free_Referral::OPTION);}else{update_option(YOWCL_Free_Referral::OPTION,$saved);}unset($_COOKIE['yowcl_ref']);}
