<?php
require __DIR__ . '/assertions.php';
global $wpdb;
$names=array(YOWCL_Free_Referral::OPTION,'loyalty_extra_points_rules','loyalty_extra_reviews_gamification_rules',YOWCL_Free_First_Purchase::RULES,YOWCL_Free_First_Purchase::WITNESS);
$saved=array();foreach($names as$n){$saved[$n]=get_option($n,null);} $actor=get_current_user_id();wp_set_current_user(1);
function rf_user($name){$u=wp_insert_user(array('user_login'=>'rf_'.$name,'user_email'=>'rf_'.$name.'@example.invalid','user_pass'=>'disposable-only','role'=>'customer'));loyf_assert(!is_wp_error($u),'Referral customer');return(int)$u;}
function rf_order($u,$date=null){$o=wc_create_order(array('customer_id'=>$u));$o->set_created_via('checkout');if($date){$o->set_date_created($date);}$o->save();return$o;}
function rf_key($o){return'referral:link:'.$o->get_id().':referrer';}
function rf_row($o){return YOWCL_Points_Transaction::find(rf_key($o));}
function rf_attach($o,$token){$_COOKIE['yowcl_ref']=$token;do_action('woocommerce_checkout_order_created',$o);$o=wc_get_order($o->get_id());$o->read_meta_data(true);return$o;}
function rf_drain($o){for($loop=0;$loop<3;$loop++){$ids=as_get_scheduled_actions(array('hook'=>YOWCL_Referral_Rewards::RETRY,'group'=>YOWCL_Referral_Rewards::GROUP,'status'=>'pending','per_page'=>100),'ids');$any=false;foreach($ids as$id){$a=ActionScheduler::store()->fetch_action($id);if((int)$a->get_args()[0]!==$o->get_id()){continue;}ActionScheduler::runner()->process_action($id,'LOYF10');$any=true;}if(!$any){break;}}}
try{
 update_option('loyalty_extra_points_rules',array('signup_enabled'=>'no','login_enabled'=>'no'));update_option('loyalty_extra_reviews_gamification_rules',array('levelup_enabled'=>'no'));YOWCL_Free_First_Purchase::save(false,0);
 $premium=array('loyalty_referral_link'=>array('enabled'=>'yes','referee_points'=>array('customer'=>900),'referrer_points'=>array('customer'=>700)),'loyalty_referral_coupon'=>array('enabled'=>'yes'),'loyalty_referral_rules'=>array('reward_frequency'=>'every_order'));foreach($premium as$n=>$v){update_option($n,$v);}
 foreach(array('','1.5','100000000',array(25),-1)as$v){update_option(YOWCL_Free_Referral::OPTION,array('enabled'=>'yes','points'=>$v));loyf_equal(false,YOWCL_Free_Referral::settings()['enabled'],'Invalid amount ineffective');}
 YOWCL_Free_Referral::save(true,0);loyf_equal(false,YOWCL_Free_Referral::settings()['enabled'],'Zero ineffective');YOWCL_Free_Referral::save(true,31);
 $a=rf_user('referrer');$b=rf_user('other');$ta=YOWCL_Helper_Referrals::ensure_user_token($a);$tb=YOWCL_Helper_Referrals::ensure_user_token($b);loyf_assert((bool)preg_match('/^[a-zA-Z0-9]{12}$/D',$ta),'Opaque shape');loyf_equal($ta,YOWCL_Helper_Referrals::ensure_user_token($a),'Reuse valid token');loyf_assert($ta!==$tb,'Unique tokens');loyf_equal(0,YOWCL_Helper_Referrals::resolve_referrer_user_id((string)$a),'Numeric ID denied');loyf_equal(0,YOWCL_Helper_Referrals::resolve_referrer_user_id('malformed'),'Malformed denied');
 $dup=rf_user('duplicate');add_user_meta($dup,'_yo_referral_token',$ta);loyf_equal(0,YOWCL_Helper_Referrals::resolve_referrer_user_id($ta),'Duplicate token denied');delete_user_meta($dup,'_yo_referral_token');add_user_meta($a,'_yo_referral_token','otherTOKEN12');loyf_equal(0,YOWCL_Helper_Referrals::resolve_referrer_user_id($ta),'Duplicate rows denied');delete_user_meta($a,'_yo_referral_token','otherTOKEN12');
 $old=rf_user('old_token');add_user_meta($old,'_yo_referral_token','OldTOKEN1234');loyf_equal('OldTOKEN1234',YOWCL_Helper_Referrals::ensure_user_token($old),'Predating valid token preserved');
 $_COOKIE['yowcl_ref']=$ta;$u=rf_user('happy');$o=rf_attach(rf_order($u),$ta);loyf_equal(31,$o->get_meta(YOWCL_Referral_Rewards::TERMS)['events'][0]['points'],'Final receipt');$_COOKIE['yowcl_ref']=$tb;YOWCL_Free_Referral::save(false,90);$o->update_status('processing');$o->update_status('completed');do_action('woocommerce_payment_complete',$o->get_id());rf_drain($o);loyf_assert(rf_row($o),'Canonical award');loyf_balance($a,31,31,'Fixed frozen referrer');loyf_balance($b,0,0,'Changed cookie no value');loyf_balance($u,0,0,'No referee bonus');loyf_equal($o->get_id(),(int)get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,true),'Winner retained');
 $before=loyf_rows($a);$fresh=wc_get_order($o->get_id());$fresh->delete_meta_data('_yo_link_referrer_awarded');$fresh->save_meta_data();YOWCL_Referral_Rewards::process($o->get_id());loyf_equal($before,loyf_rows($a),'Committed repair no mutation');loyf_equal('yes',wc_get_order($o->get_id())->get_meta('_yo_link_referrer_awarded'),'Component marker restored');
 YOWCL_Points_Transaction::apply($a,-20,0,'rf:spend');$o->update_status('cancelled');rf_drain($o);$rev=YOWCL_Points_Transaction::find(rf_key($o).':reversal');loyf_assert($rev,'Canonical reversal');loyf_equal(-11,(int)$rev['available_delta'],'Partial spend available clamp');loyf_equal(-31,(int)$rev['earning_delta'],'Independent earning clamp');loyf_equal(rf_key($o),$rev['source_event_key'],'Exact source');YOWCL_Points_Transaction::apply($a,50,50,'rf:later');$o->update_status('refunded');$o->update_status('failed');rf_drain($o);loyf_balance($a,50,50,'Terminal replay preserves later credit');
 YOWCL_Free_Referral::save(true,31);
 foreach(array('guest','self','disabled','invalid','none')as$case){$owner='guest'===$case?0:('self'===$case?$b:rf_user($case));if('disabled'===$case){YOWCL_Free_Referral::save(false,31);}$x=rf_attach(rf_order($owner),'invalid'===$case?(string)$a:('none'===$case?'':$tb));YOWCL_Free_Referral::save(true,31);$_COOKIE['yowcl_ref']=$ta;$x->update_status('processing');rf_drain($x);loyf_equal(null,rf_row($x),'No retroactive value '.$case);}
 // Non-referred and historical first success consume eligibility, even after later deletion.
 foreach(array('nonreferred','historical')as$case){$u=rf_user($case);$first=rf_order($u,time()-500);if('nonreferred'===$case){$first=rf_attach($first,'');}$first->update_status('processing');$second=rf_attach(rf_order($u,time()-100),$tb);$second->update_status('processing');rf_drain($second);loyf_equal(null,rf_row($second),'Earlier consumes '.$case);loyf_equal($first->get_id(),(int)get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,true),'Earlier witness '.$case);$first->delete(true);$third=rf_attach(rf_order($u),$tb);$third->update_status('processing');rf_drain($third);loyf_equal(null,rf_row($third),'Deleted winner not reopened');}
 // Frozen value under native recipient contention, terminal before commit, zero reversal replay.
 foreach(array('retry','terminal','zero')as$case){$r=rf_user('r_'.$case);$t=YOWCL_Helper_Referrals::ensure_user_token($r);$x=rf_attach(rf_order(rf_user('u_'.$case)),$t);$lock=YOWCL_Points_Lock::acquire($r);try{$x->update_status('processing');loyf_equal(null,rf_row($x),'Native lock holds value');YOWCL_Free_Referral::save(false,90);}finally{YOWCL_Points_Lock::release($lock);}if('terminal'===$case){$x->update_status('cancelled');}rf_drain($x);YOWCL_Free_Referral::save(true,31);if('terminal'===$case){loyf_equal(null,rf_row($x),'Terminal before commit denied');continue;}loyf_balance($r,31,31,'Retained frozen retry');if('zero'===$case){YOWCL_Points_Transaction::apply($r,-31,-31,'rf:zero');}$x->update_status('refunded');rf_drain($x);loyf_balance($r,0,0,'Full or zero reversal');$rr=YOWCL_Points_Transaction::find(rf_key($x).':reversal');loyf_assert($rr,'Zero committed terminal');YOWCL_Points_Transaction::apply($r,7,7,'rf:replenish:'.$r);YOWCL_Referral_Rewards::process($x->get_id());loyf_balance($r,7,7,'No later unrelated deduction');}
 // Independent First Purchase and Referral Lite recipients/terminal policies.
 $r=rf_user('coexist_r');$t=YOWCL_Helper_Referrals::ensure_user_token($r);YOWCL_Free_First_Purchase::save(true,17);$u=rf_user('coexist_u');$x=rf_order($u,time()+1);$x=rf_attach($x,$t);$x->update_status('processing');rf_drain($x);loyf_balance($u,17,17,'First Purchase distinct recipient');loyf_balance($r,31,31,'Referral distinct recipient');$x->update_status('cancelled');rf_drain($x);loyf_balance($u,17,17,'No First Purchase clawback');loyf_balance($r,0,0,'Referral clawback');YOWCL_Free_First_Purchase::save(false,0);
 // Copy/render are observational; malicious Premium components cannot create value.
 wp_set_current_user($b);$rows=loyf_rows($b);ob_start();YOWCL_Free_Referral::render_link('test');$html=ob_get_clean();loyf_assert(strpos($html,'?ref='.$tb)!==false&&strpos($html,'data-loyf-referral-copy')!==false,'Basic current customer link');loyf_equal($rows,loyf_rows($b),'Render no accounting');wp_set_current_user(1);
 $x=rf_attach(rf_order(rf_user('forbidden')),$tb);$terms=$x->get_meta(YOWCL_Referral_Rewards::TERMS);$terms['events'][0]['action']='referral_link_referee_reward';YOWCL_Order_Rewards::meta($x,YOWCL_Referral_Rewards::TERMS,$terms);$x->update_status('processing');loyf_equal(null,rf_row($x),'Unsupported referee value denied');foreach($premium as$n=>$v){loyf_equal($v,get_option($n),'Premium option untouched');}
 fwrite(STDOUT,'Native Referral Lite '.getenv('LOYF_STORAGE').' PASS Woo'.WC_VERSION.' WP'.get_bloginfo('version')."\n");
}finally{foreach($saved as$n=>$v){if(null===$v){delete_option($n);}else{update_option($n,$v);}}wp_set_current_user($actor);unset($_COOKIE['yowcl_ref']);}
