<?php
require __DIR__ . '/assertions.php';
global $wpdb;
$names=array(YOWCL_Free_Referral::OPTION,'loyalty_extra_points_rules','loyalty_extra_reviews_gamification_rules',YOWCL_Free_First_Purchase::RULES,YOWCL_Free_First_Purchase::WITNESS);
$saved=array();foreach($names as$n){$saved[$n]=get_option($n,null);} $actor=get_current_user_id();wp_set_current_user(1);
function rf_user($name){$u=wp_insert_user(array('user_login'=>'rf_'.$name,'user_email'=>'rf_'.$name.'@example.invalid','user_pass'=>'disposable-only','role'=>'customer'));loyf_assert(!is_wp_error($u),'Referral customer');return(int)$u;}
function rf_order($u,$date=null){$o=wc_create_order(array('customer_id'=>$u));$o->set_created_via('checkout');if($date){$o->set_date_created($date);}$o->save();return$o;}
function rf_key($o){return'referral:link:'.$o->get_id().':referrer';}
function rf_row($o){return YOWCL_Points_Transaction::find(rf_key($o));}
function rf_attach($o,$token){$_COOKIE['yowcl_ref']=$token;do_action('woocommerce_checkout_order_created',$o);$o=wc_get_order($o->get_id());$o->read_meta_data(true);return$o;}
function rf_drain($o){for($loop=0;$loop<3;$loop++){$ids=as_get_scheduled_actions(array('hook'=>YOWCL_Referral_Rewards::RETRY,'group'=>YOWCL_Referral_Rewards::GROUP,'status'=>'pending','per_page'=>100),'ids');$any=false;foreach($ids as$id){$a=ActionScheduler::store()->fetch_action($id);if((int)$a->get_args()[0]!==$o->get_id()){continue;}ActionScheduler::runner()->process_action($id,'LOYF10');$any=true;}if(!$any){break;}}}
try{
 update_option('loyalty_extra_points_rules',array('signup_enabled'=>'no','login_enabled'=>'no'));update_option('loyalty_extra_reviews_gamification_rules',array('levelup_enabled'=>'no'));YOWCL_Free_First_Purchase::save(false,0);
 $premium=array('loyalty_referral_link'=>array('enabled'=>'yes','referee_points'=>array('customer'=>900),'referrer_points'=>array('customer'=>700)),'loyalty_referral_coupon'=>array('enabled'=>'yes'),'loyalty_referral_rules'=>array('reward_frequency'=>'every_order'));foreach($premium as$n=>$v){update_option($n,$v);}
 foreach(array('','1.5','100000000',array(25),-1)as$v){update_option(YOWCL_Free_Referral::OPTION,array('enabled'=>'yes','points'=>$v));loyf_equal(false,YOWCL_Free_Referral::settings()['enabled'],'Invalid amount ineffective');}
 YOWCL_Free_Referral::save(true,0);loyf_equal(false,YOWCL_Free_Referral::settings()['enabled'],'Zero ineffective');YOWCL_Free_Referral::save(true,31);
 $a=rf_user('referrer');$b=rf_user('other');$ta=YOWCL_Helper_Referrals::ensure_user_token($a);$tb=YOWCL_Helper_Referrals::ensure_user_token($b);loyf_assert((bool)preg_match('/^[a-zA-Z0-9]{12}$/D',$ta),'Opaque shape');loyf_equal($ta,YOWCL_Helper_Referrals::ensure_user_token($a),'Reuse valid token');loyf_assert($ta!==$tb,'Unique tokens');loyf_equal(0,YOWCL_Helper_Referrals::resolve_referrer_user_id((string)$a),'Numeric ID denied');loyf_equal(0,YOWCL_Helper_Referrals::resolve_referrer_user_id('malformed'),'Malformed denied');
 $dup=rf_user('duplicate');add_user_meta($dup,'_yo_referral_token',$ta);loyf_equal(0,YOWCL_Helper_Referrals::resolve_referrer_user_id($ta),'Duplicate token denied');delete_user_meta($dup,'_yo_referral_token');add_user_meta($a,'_yo_referral_token','otherTOKEN12');loyf_equal(0,YOWCL_Helper_Referrals::resolve_referrer_user_id($ta),'Duplicate rows denied');delete_user_meta($a,'_yo_referral_token','otherTOKEN12');
 $u=rf_user('token_race');$barrier=tempnam(sys_get_temp_dir(),'loyf10-token-');unlink($barrier);$workers=array();foreach(array(0,1)as$i){$env=getenv();$env['LOYF10_TOKEN_USER']=(string)$u;$env['LOYF10_TOKEN_INDEX']=(string)$i;$env['LOYF10_TOKEN_BARRIER']=$barrier;$pipes=array();$p=proc_open(array(PHP_BINARY,getenv('LOYF_WP_CLI_PHAR'),'--path='.ABSPATH,'eval-file',__DIR__.'/referral-token-worker.php','--quiet'),array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('pipe','w')),$pipes,null,$env);loyf_assert(is_resource($p),'Native token worker');fclose($pipes[0]);$workers[]=array($p,$pipes);}$tokens=array();try{foreach($workers as$w){$out=stream_get_contents($w[1][1]);$err=stream_get_contents($w[1][2]);fclose($w[1][1]);fclose($w[1][2]);loyf_equal(0,proc_close($w[0]),'Concurrent token '.$err);$tokens[]=trim($out);}}finally{foreach(array('.0','.1')as$suffix){if(file_exists($barrier.$suffix)){unlink($barrier.$suffix);}}}loyf_equal($tokens[0],$tokens[1],'Primed-cache creators reuse one token');wp_cache_delete($u,'user_meta');loyf_equal(array($tokens[0]),get_user_meta($u,'_yo_referral_token',false),'One persistent token row');
 $old=rf_user('old_token');add_user_meta($old,'_yo_referral_token','OldTOKEN1234');loyf_equal('OldTOKEN1234',YOWCL_Helper_Referrals::ensure_user_token($old),'Predating valid token preserved');
 $_COOKIE['yowcl_ref']=$ta;$u=rf_user('happy');$o=rf_attach(rf_order($u),$ta);loyf_equal(31,$o->get_meta(YOWCL_Referral_Rewards::TERMS)['events'][0]['points'],'Final receipt');$_COOKIE['yowcl_ref']=$tb;YOWCL_Free_Referral::save(false,90);$o->update_status('processing');$o->update_status('completed');do_action('woocommerce_payment_complete',$o->get_id());rf_drain($o);loyf_assert(rf_row($o),'Canonical award');loyf_balance($a,31,31,'Fixed frozen referrer');loyf_balance($b,0,0,'Changed cookie no value');loyf_balance($u,0,0,'No referee bonus');loyf_equal($o->get_id(),(int)get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,true),'Winner retained');
 $before=loyf_rows($a);$fresh=wc_get_order($o->get_id());$fresh->delete_meta_data('_yo_link_referrer_awarded');$fresh->save_meta_data();YOWCL_Referral_Rewards::process($o->get_id());loyf_equal($before,loyf_rows($a),'Committed repair no mutation');loyf_equal('yes',wc_get_order($o->get_id())->get_meta('_yo_link_referrer_awarded'),'Component marker restored');
 add_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,'malformed',false);YOWCL_Points_Transaction::apply($a,-20,0,'rf:spend');$o->update_status('cancelled');rf_drain($o);$rev=YOWCL_Points_Transaction::find(rf_key($o).':reversal');loyf_assert($rev,'Canonical reversal');loyf_equal(-11,(int)$rev['available_delta'],'Partial spend available clamp');loyf_equal(-31,(int)$rev['earning_delta'],'Independent earning clamp');loyf_equal(rf_key($o),$rev['source_event_key'],'Exact source');YOWCL_Points_Transaction::apply($a,50,50,'rf:later');$o->update_status('refunded');$o->update_status('failed');rf_drain($o);loyf_balance($a,50,50,'Terminal replay preserves later credit');
 wp_set_current_user($b);ob_start();YOWCL_Free_Referral::render_link('disabled');$off=ob_get_clean();loyf_equal('',$off,'Disabled has no empty referral link');wp_set_current_user(1);
 YOWCL_Free_Referral::save(true,31);
 foreach(array('guest','self','disabled','invalid','none')as$case){$owner='guest'===$case?0:('self'===$case?$b:rf_user($case));if('disabled'===$case){YOWCL_Free_Referral::save(false,31);}$x=rf_attach(rf_order($owner),'invalid'===$case?(string)$a:('none'===$case?'':$tb));YOWCL_Free_Referral::save(true,31);$_COOKIE['yowcl_ref']=$ta;$x->update_status('processing');rf_drain($x);loyf_equal(null,rf_row($x),'No retroactive value '.$case);}
 // Non-referred and historical first success consume eligibility, even after later deletion.
 foreach(array('nonreferred','historical')as$case){$u=rf_user($case);$first=rf_order($u,time()-500);if('nonreferred'===$case){$first=rf_attach($first,'');}$hooks=clone $GLOBALS['wp_filter']['woocommerce_order_status_changed'];if('historical'===$case){remove_all_actions('woocommerce_order_status_changed');}try{$first->update_status('processing');}finally{$GLOBALS['wp_filter']['woocommerce_order_status_changed']=$hooks;}$second=rf_attach(rf_order($u,time()-100),$tb);$second->update_status('processing');rf_drain($second);loyf_equal(null,rf_row($second),'Earlier consumes '.$case);loyf_equal($first->get_id(),(int)get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,true),'Earlier witness '.$case);$first->delete(true);$third=rf_attach(rf_order($u),$tb);$third->update_status('processing');rf_drain($third);loyf_equal(null,rf_row($third),'Deleted winner not reopened');}
 // Malformed identity must not hide native-owned historical first successes from election.
 foreach(array('orphan','qualified','foreign_identity','duplicate_identity')as$case){
  $u=rf_user('identity_'.$case);$first=rf_order($u,time()-500);
  $hooks=clone $GLOBALS['wp_filter']['woocommerce_order_status_changed'];remove_all_actions('woocommerce_order_status_changed');
  try{$first->update_status('processing');}finally{$GLOBALS['wp_filter']['woocommerce_order_status_changed']=$hooks;}
  $identity='foreign_identity'===$case?'user:'.$b:'broken';
  $first->add_meta_data(YOWCL_Referral_Rewards::IDENTITY,$identity);
  if('duplicate_identity'===$case){$first->add_meta_data(YOWCL_Referral_Rewards::IDENTITY,'user:'.$u);}
  if('qualified'===$case){$first->add_meta_data(YOWCL_Referral_Rewards::QUALIFIED,array('identity'=>'broken','referee'=>$u,'email'=>'','frequency'=>'first_order','award_statuses'=>array('wc-processing','wc-completed')));}
  $first->save_meta_data();$foreign_claim=get_user_meta($b,YOWCL_Referral_Rewards::USER_WINNER,false);
  $second=rf_attach(rf_order($u,time()-100),$tb);$second->update_status('processing');
  loyf_equal(null,rf_row($second),'Hidden malformed history no value '.$case);
  loyf_equal(array(),get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,false),'Ambiguous history no claim '.$case);
  loyf_equal($foreign_claim,get_user_meta($b,YOWCL_Referral_Rewards::USER_WINNER,false),'Identity cannot transfer claim '.$case);
  $first->delete_meta_data(YOWCL_Referral_Rewards::IDENTITY);$first->delete_meta_data(YOWCL_Referral_Rewards::QUALIFIED);$first->add_meta_data(YOWCL_Referral_Rewards::IDENTITY,'user:'.$u);$first->save_meta_data();
  rf_drain($second);YOWCL_Referral_Rewards::process($second->get_id());
  loyf_equal(null,rf_row($second),'Repaired identity preserves first success '.$case);
  loyf_equal($first->get_id(),(int)get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,true),'Repaired historical winner '.$case);
 }
 // Valid final ownership remains frozen when the live order owner is subsequently edited.
 foreach(array('receipt','qualified_receipt')as$case){
  $original=rf_user('frozen_original_'.$case);$edited=rf_user('frozen_edited_'.$case);$first=rf_attach(rf_order($original,time()-500),'');
  $hooks=clone $GLOBALS['wp_filter']['woocommerce_order_status_changed'];remove_all_actions('woocommerce_order_status_changed');
  try{$first->update_status('processing');}finally{$GLOBALS['wp_filter']['woocommerce_order_status_changed']=$hooks;}
  if('qualified_receipt'===$case){YOWCL_Referral_Rewards::record_transition($first->get_id(),'processing');}
  $first=wc_get_order($first->get_id());$first->set_customer_id($edited);$first->save();
  $later=rf_attach(rf_order($original,time()-100),$tb);$later->update_status('processing');loyf_equal(null,rf_row($later),'Frozen original first consumed '.$case);
  loyf_equal($first->get_id(),(int)get_user_meta($original,YOWCL_Referral_Rewards::USER_WINNER,true),'Frozen original witness '.$case);
  $later=rf_attach(rf_order($edited),$tb);$later->update_status('processing');loyf_assert(rf_row($later),'Validated foreign frozen owner excluded '.$case);
 }
 // Frozen value under native recipient contention, terminal before commit, zero reversal replay.
 foreach(array('retry','terminal','zero')as$case){$r=rf_user('r_'.$case);$t=YOWCL_Helper_Referrals::ensure_user_token($r);$x=rf_attach(rf_order(rf_user('u_'.$case)),$t);$lock=YOWCL_Points_Lock::acquire($r);try{$x->update_status('processing');loyf_equal(null,rf_row($x),'Native lock holds value');YOWCL_Free_Referral::save(false,90);}finally{YOWCL_Points_Lock::release($lock);}if('terminal'===$case){$x->update_status('cancelled');}rf_drain($x);YOWCL_Free_Referral::save(true,31);if('terminal'===$case){loyf_equal(null,rf_row($x),'Terminal before commit denied');continue;}loyf_balance($r,31,31,'Retained frozen retry');if('zero'===$case){YOWCL_Points_Transaction::apply($r,-31,-31,'rf:zero');}$x->update_status('refunded');rf_drain($x);loyf_balance($r,0,0,'Full or zero reversal');$rr=YOWCL_Points_Transaction::find(rf_key($x).':reversal');loyf_assert($rr,'Zero committed terminal');YOWCL_Points_Transaction::apply($r,7,7,'rf:replenish:'.$r);YOWCL_Referral_Rewards::process($x->get_id());loyf_balance($r,7,7,'No later unrelated deduction');}
 // Unknown response after actual COMMIT and exactly-once terminal recovery.
 $r=rf_user('unknown_r');$t=YOWCL_Helper_Referrals::ensure_user_token($r);$x=rf_attach(rf_order(rf_user('unknown_u')),$t);$fault=function($step){if('commit_response'===$step){throw new RuntimeException('Referral lost commit response');}};add_action('yowcl_transaction_test_checkpoint',$fault);$x->update_status('processing');remove_action('yowcl_transaction_test_checkpoint',$fault);$before=loyf_rows($r);loyf_equal(1,count($before),'Unknown committed once');rf_drain($x);loyf_equal($before,loyf_rows($r),'Unknown replay unchanged');
 // Later callback acquires election first; both successes exist before serialized election.
 $r=rf_user('race_r');$u=rf_user('race_u');$t=YOWCL_Helper_Referrals::ensure_user_token($r);$earlier=rf_attach(rf_order($u,time()-200),$t);$later=rf_attach(rf_order($u,time()-100),$t);
 $db=new mysqli(getenv('LOY_DB_HOST'),getenv('LOY_DB_USER'),getenv('LOY_DB_PASSWORD'),DB_NAME,(int)getenv('LOY_DB_PORT'));$name='yowclrf_'.hash('sha224',DB_NAME.':'.$wpdb->prefix.':user:'.$u);loyf_equal('1',(string)YOWCL_Points_Lock::scalar($db,$wpdb->prepare('SELECT GET_LOCK(%s,0)',$name)),'External election owner');try{$later->update_status('processing');$earlier->update_status('processing');loyf_equal(null,rf_row($earlier),'Election contention no value');}finally{YOWCL_Points_Lock::scalar($db,$wpdb->prepare('SELECT RELEASE_LOCK(%s)',$name));$db->close();}
 $barrier=tempnam(sys_get_temp_dir(),'loyf10-race-');unlink($barrier);$workers=array();foreach(array($later,$earlier)as$i=>$o){$env=getenv();$env['LOYF10_ORDER']=(string)$o->get_id();$env['LOYF10_INDEX']=(string)$i;$env['LOYF10_BARRIER']=$barrier;$pipes=array();$p=proc_open(array(PHP_BINARY,getenv('LOYF_WP_CLI_PHAR'),'--path='.ABSPATH,'eval-file',__DIR__.'/referral-worker.php','--quiet'),array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('pipe','w')),$pipes,null,$env);loyf_assert(is_resource($p),'Referral native worker');fclose($pipes[0]);$workers[]=array($p,$pipes);}try{foreach($workers as$w){$out=stream_get_contents($w[1][1]);$err=stream_get_contents($w[1][2]);fclose($w[1][1]);fclose($w[1][2]);loyf_equal(0,proc_close($w[0]),'Referral race '.$out.$err);}}finally{if(file_exists($barrier)){unlink($barrier);}}wp_cache_delete($u,'user_meta');wp_cache_delete($r,'user_meta');rf_drain($earlier);rf_drain($later);loyf_equal($earlier->get_id(),(int)get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,true),'Deterministic earliest winner');loyf_assert(rf_row($earlier),'Earlier award');loyf_equal(null,rf_row($later),'Later no event');loyf_balance($r,31,31,'Concurrent one value');
 // Independent First Purchase and Referral Lite recipients/terminal policies.
 $r=rf_user('coexist_r');$t=YOWCL_Helper_Referrals::ensure_user_token($r);YOWCL_Free_First_Purchase::save(true,17);$u=rf_user('coexist_u');$x=rf_order($u,time()+1);$x=rf_attach($x,$t);$x->update_status('processing');rf_drain($x);loyf_balance($u,17,17,'First Purchase distinct recipient');loyf_balance($r,31,31,'Referral distinct recipient');$x->update_status('cancelled');rf_drain($x);loyf_balance($u,17,17,'No First Purchase clawback');loyf_balance($r,0,0,'Referral clawback');YOWCL_Free_First_Purchase::save(false,0);
 // A poisoned qualification cannot transfer election authority or erase a non-referred first success.
 $u=rf_user('poison');$first=rf_order($u,time()-500);$bad=array('identity'=>'user:'.$b,'referee'=>$b,'email'=>'','frequency'=>'first_order','award_statuses'=>array('wc-processing','wc-completed'));YOWCL_Order_Rewards::meta($first,YOWCL_Referral_Rewards::QUALIFIED,$bad);YOWCL_Order_Rewards::meta($first,YOWCL_Referral_Rewards::IDENTITY,'user:'.$u);$claim=get_user_meta($b,YOWCL_Referral_Rewards::USER_WINNER,false);$first->update_status('processing');loyf_equal($claim,get_user_meta($b,YOWCL_Referral_Rewards::USER_WINNER,false),'No foreign customer claim');$second=rf_attach(rf_order($u),$tb);$second->update_status('processing');loyf_equal(null,rf_row($second),'Malformed history cannot admit later value');$bad['identity']='user:'.$u;$bad['referee']=$u;YOWCL_Order_Rewards::meta($first,YOWCL_Referral_Rewards::QUALIFIED,$bad);rf_drain($second);loyf_equal(null,rf_row($second),'Repaired history suppresses later referral');loyf_equal($first->get_id(),(int)get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,true),'Repaired correct witness');
 // Persisted empty/duplicate receipts are distinct from absence at every admission/retry path.
 foreach(array('empty','empty_valid','valid_empty','empty_unsupported','duplicate_valid')as$case){
  $u=rf_user('receipt_'.$case);$x=rf_order($u,time()-500);$_COOKIE['yowcl_ref']=$ta;$frozen=YOWCL_Free_Referral::discover($x);
  $unsupported=$frozen;$unsupported['channel']='coupon';$unsupported['coupons']=array(array('id'=>123,'code'=>'dormant'));
  $values='empty'===$case?array(''):('empty_valid'===$case?array('',$frozen):('valid_empty'===$case?array($frozen,''):('empty_unsupported'===$case?array('',$unsupported):array($frozen,$frozen))));
  foreach($values as$value){$x->add_meta_data(YOWCL_Referral_Rewards::TERMS,$value);}$x->save_meta_data();$x->read_meta_data(true);
  $snapshot=static function($o){$o->read_meta_data(true);return array_map(static function($m){return $m->get_data();},array_values($o->get_meta(YOWCL_Referral_Rewards::TERMS,false,'edit')));};$before=$snapshot($x);
  YOWCL_Free_Referral::save(true,99);$_COOKIE['yowcl_ref']=$tb;
  try{do_action('woocommerce_checkout_order_created',$x);throw new LogicException('Ambiguous attachment admitted');}catch(RuntimeException$e){loyf_equal('referral_attribution_not_saved',$e->getMessage(),'Final receipt held '.$case);}
  $x=wc_get_order($x->get_id());$x->update_status('processing');$x->update_status('completed');YOWCL_Referral_Rewards::queue($x->get_id());rf_drain($x);$x->update_status('cancelled');
  loyf_equal($before,$snapshot($x),'All receipt rows preserved '.$case);loyf_equal(null,rf_row($x),'Ambiguous receipt no value '.$case);
  foreach(array(YOWCL_Referral_Rewards::IDENTITY,YOWCL_Referral_Rewards::QUALIFIED,YOWCL_Referral_Rewards::TERMINAL,'_yo_link_referrer_awarded')as$key){loyf_equal('',$x->get_meta($key),'No receipt-derived mutation '.$case);}
  loyf_equal(array(),get_user_meta($u,YOWCL_Referral_Rewards::USER_WINNER,false),'No ambiguous receipt claim '.$case);
  $later=rf_attach(rf_order($u),$tb);$later->update_status('processing');loyf_equal(null,rf_row($later),'Ambiguous first receipt cannot erase history '.$case);
  YOWCL_Free_Referral::save(true,31);
 }
 // Dormant Premium receipts and legacy attribution remain byte-equivalent, with no synthetic value.
 $x=rf_order(rf_user('foreign'));$foreign=YOWCL_Free_Referral::discover($x);$foreign['channel']='coupon';$foreign['coupons']=array(array('id'=>123,'code'=>'dormant'));YOWCL_Order_Rewards::meta($x,YOWCL_Referral_Rewards::TERMS,$foreign);$x->update_status('cancelled');$x=wc_get_order($x->get_id());$x->read_meta_data(true);loyf_equal($foreign,$x->get_meta(YOWCL_Referral_Rewards::TERMS),'Foreign receipt untouched');loyf_equal('',$x->get_meta(YOWCL_Referral_Rewards::TERMINAL),'Foreign terminal untouched');loyf_equal('',$x->get_meta(YOWCL_Referral_Rewards::QUALIFIED),'Foreign qualification untouched');
 $x=rf_order(rf_user('legacy'));YOWCL_Order_Rewards::meta($x,'_yo_link_referrer_user_id',$a);YOWCL_Order_Rewards::meta($x,'_yo_link_referrer_awarded','yes');$x=rf_attach($x,$tb);loyf_equal('',$x->get_meta(YOWCL_Referral_Rewards::TERMS),'Legacy no new attribution receipt');loyf_equal($a,(int)$x->get_meta('_yo_link_referrer_user_id'),'Legacy referrer preserved');$x->update_status('processing');loyf_equal(null,rf_row($x),'Legacy no positive backfill');
 // Native privileged form capability and nonce guards preserve all options.
 $prior=get_option(YOWCL_Free_Referral::OPTION);foreach(array('nonce','capability')as$deny){wp_set_current_user('nonce'===$deny?1:$b);$_POST=array('loyf_referral_save'=>1,'loyf_referral_points'=>99,'loyf_referral_enabled'=>'yes','loyf_referral_nonce'=>'nonce'===$deny?'bad':wp_create_nonce('loyf_referral_save'));$die=function(){return function($message){throw new LOYF_Test_Die((string)$message);};};add_filter('wp_die_handler',$die,PHP_INT_MAX);add_filter('wp_die_ajax_handler',$die,PHP_INT_MAX);try{do_action('admin_init');throw new RuntimeException('Denied form accepted');}catch(LOYF_Test_Die$e){loyf_equal('referral_save_denied',$e->getMessage(),'Native denial');}finally{remove_filter('wp_die_handler',$die,PHP_INT_MAX);remove_filter('wp_die_ajax_handler',$die,PHP_INT_MAX);$_POST=array();}loyf_equal($prior,get_option(YOWCL_Free_Referral::OPTION),'Denied settings unchanged');}wp_set_current_user(1);
 // Copy/render are observational; malicious Premium components cannot create value.
 wp_set_current_user($b);$rows=loyf_rows($b);ob_start();YOWCL_Free_Referral::render_link('test');$html=ob_get_clean();loyf_assert(strpos($html,'?ref='.$tb)!==false&&strpos($html,'data-loyf-referral-copy')!==false,'Basic current customer link');loyf_equal($rows,loyf_rows($b),'Render no accounting');wp_set_current_user(1);
 $x=rf_attach(rf_order(rf_user('forbidden')),$tb);$terms=$x->get_meta(YOWCL_Referral_Rewards::TERMS);$terms['events'][0]['action']='referral_link_referee_reward';YOWCL_Order_Rewards::meta($x,YOWCL_Referral_Rewards::TERMS,$terms);$x->update_status('processing');loyf_equal(null,rf_row($x),'Unsupported referee value denied');foreach($premium as$n=>$v){loyf_equal($v,get_option($n),'Premium option untouched');}
 $identity_rows=$wpdb->get_results("SELECT * FROM ".YOWCL_Points_Log::table_name()." WHERE action IN ('referral_link_referrer_reward','referral_reward_reversal') ORDER BY id",ARRAY_A);require __DIR__.'/upstream-replay.php';
 fwrite(STDOUT,'Native Referral Lite '.getenv('LOYF_STORAGE').' PASS Woo'.WC_VERSION.' WP'.get_bloginfo('version')."\n");
}finally{foreach($saved as$n=>$v){if(null===$v){delete_option($n);}else{update_option($n,$v);}}wp_set_current_user($actor);unset($_COOKIE['yowcl_ref']);}
